# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-windows-implement-0.60.0.tar.gz/sha256/0dm88k3hlaax85xkls4gf597ar4z8m5vzjjagzk910ph7b8xszx4" "https://crates.io/api/v1/crates/windows-implement/0.60.0/download" ]; hash = "sha256-pH/d0TrwgpDmf0rKv0tFn2R1UnGPaDp7QV0pCsdEqDY="; name = "rust-windows-implement-0.60.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/wsalv18mqbyrzmll0qyqr4apj30hi9m7-rust-windows-implement-0.60.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
