# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "acl-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''acl-runtime-env-builder''; path = ./../sources/rb8qv842swavxszp2z9fk6nsvzzr3wan-acl-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "acl-runtime-env-builder"; path = ./../sources/rb8qv842swavxszp2z9fk6nsvzzr3wan-acl-runtime-env-builder; })
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/qqzn4qa0nrb0vazm51n04pwwp1dzyv6j-acl-2.3.1.nix).out} ${(import ../store/4k83zn8nl8f0mbd3p2p6b68dz8gwadi2-attr-2.5.1.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/03ik48x9xg0q9izjgpm6wlis6ypcdfs7-acl-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
