# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://gitlab.freedesktop.org/mesa/glu"; rev = "refs/tags/glu-9.0.2"; hash = "sha256-edHQZoKHE6UY/Jo9Hz4bAkFVgMy7D4eaJ/3S51t0Hc4="; name = "glu-9.0.2-checkout"; guixHash = "f3g72k8rfr75d6xdx0176i7rlc1phxnr"; fetchSubmodules = false; }
