# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-env-logger-0.10.2.tar.gz/sha256/1005v71kay9kbz1d5907l0y7vh9qn2fqsp2yfgb8bjvin6m0bm2c" "https://crates.io/api/v1/crates/env_logger/0.10.2/download" ]; hash = "sha256-TNQFqrFxy4XWc15cjZ2wOMF9PKAHpNLCXzN5NcPZBYA="; name = "rust-env-logger-0.10.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/i8am0igdzhm6fa19l9rwbdjpwhpwvmx0-rust-env-logger-0.10.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
