# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "ld-wrapper-boot3-0";
    system = "x86_64-linux";
    builder = "${(import ../store/ahkdlnqj5180w9m1bi8wiqccmqvvy1a3-guile-bootstrap-2.0.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/6wf8wfl5w9bbzkcszys0qp8vahv6mmqm-module-import-compiled.nix).out}"
      "${builtins.path { name = ''ld-wrapper-boot3-0-builder''; path = ./../sources/9fyzadmxd1mz8wmvak4ls98lggazpy5w-ld-wrapper-boot3-0-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
      (builtins.path { name = "ld-wrapper-boot3-0-builder"; path = ./../sources/9fyzadmxd1mz8wmvak4ls98lggazpy5w-ld-wrapper-boot3-0-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/8j7hrx03z771a9xicrjkvz70v23ackaq-bash-mesboot-5.2.37.nix).out} ${(import ../store/0mwnw93igzmjvg46sdkh81z4v5j9q4zj-binutils-2.44.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/0g10nvzgznlghn0d6rsihb59708zn73f-ld-wrapper-boot3-0.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
