# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "texlive-listings-2025.2-checkout";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
      "-L"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
      "-L"
      "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
      "-L"
      "${(import ../store/8499853ilh8ibcsipn20zv9n538dd51y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
      "-C"
      "${(import ../store/f3fz0zg49f5sgjlss4wp7bhdv5rgylcz-module-import-compiled.nix).out}"
      "-C"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
      "-C"
      "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
      "-C"
      "${(import ../store/8499853ilh8ibcsipn20zv9n538dd51y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
      "${builtins.path { name = ''svn-multi-download''; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; }}"
    ];
    srcs = [
      (builtins.path { name = "svn-multi-download"; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; })
      (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
    ];
    outputHash = "sha256-2Y1cL1Ok+Zfd/1KVjCJoPRUKbe2lIc8oz5yjEhWT0i4=";
    outputHashAlgo = "sha256";
    outputHashMode = "recursive";
    hash = "217,141,92,47,83,164,249,151,221,255,82,149,140,34,104,61,21,10,109,237,165,33,207,40,207,156,163,18,21,147,210,46";
    impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
    preferLocalBuild = "1";
    "svn locations" = "(\"doc/latex/listings/\" \"source/latex/listings/\" \"tex/latex/listings/\")";
    "svn revision" = "74725";
    "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
    __phantom_deps = "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).debug} ${(import ../store/gqs76a403zn5d0j0n280z3rzxgf1yxr0-gzip-1.14.nix).out} ${(import ../store/h47q2hnlw8x5q16ml76kvxknsyab730j-tar-1.35.nix).out} ${(import ../store/nsy5wz63807mkcfzrp6p6mpp3jss8v9k-subversion-1.14.5.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/0iad62k5rba1jxm2dc0n550rrc307cvb-texlive-listings-2025.2-checkout.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
