# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/ImageMagick-6.9.13-5.tar.xz/sha256/1j1chkw33vjc37509vdwss28qywfvckvs73pvscldj8d0wnwypa8" "mirror://imagemagick/ImageMagick-6.9.13-5.tar.xz" ]; hash = "sha256-SF3PLQcNyUaZ3nccvSfbjnuMhNa87QTKGUzuMfiELMg="; name = "ImageMagick-6.9.13-5.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/xm291sw78phzqp2mx4h3r45zv9xs5kf0-ImageMagick-6.9.13-5.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
