# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/glib-networking-2.78.1.tar.xz/sha256/17zhkf2pjwrghdgk5nhfvzqakb2xwk2jj19316xjr0s9n3djv3z4" "https://download.gnome.org/sources/glib-networking/2.78/glib-networking-2.78.1.tar.xz" ]; hash = "sha256-5I8t27BJgyy7CSMFKcXkXayp8N8O2jJfgy9zeYWb8J8="; name = "glib-networking-2.78.1.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/gq6jrrwr0rzlh61vh2isb3p9j36rzy4h-glib-networking-2.78.1.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
