# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-servo-arc-0.3.0.tar.gz/sha256/0i0s9786np106yl6w29bfzwnj29rqak912skcdxcf04yjlddfdnh" "https://crates.io/api/v1/crates/servo_arc/0.3.0/download" ]; hash = "sha256-0DbXGpWeAMd6Y1OLkKbCOQlp+XcrCW6oNyBca9BJGkQ="; name = "rust-servo-arc-0.3.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/ggma57rscviki7y5kpx4n1qgg5sfkl0k-rust-servo-arc-0.3.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
