# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/dSFMT-src-2.2.3.tar.gz/sha256/03kaqbjbi6viz0n33dk5jlf6ayxqlsq4804n7kwkndiga9s4hd42" "http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/dSFMT-src-2.2.3.tar.gz" ]; hash = "sha256-gjRIdFIvNjv5PJYARLCmuHtlHJVltjEs+HGbuOTCag4="; name = "dSFMT-src-2.2.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/7vsvvvslsy66c9h9nfa9vriwc3yksd75-dSFMT-src-2.2.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
