# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz/sha256/0sm2z9x4wk45bh6qfs94p0w1d6hsy6dqx9sw38qsqbvxwa1qzk8s" "https://ftpmirror.gnu.org/guix/bootstrap//i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "https://ftp.gnu.org/gnu/guix/bootstrap/i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "http://ftp.gnu.org/gnu/guix/bootstrap/i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "https://alpha.gnu.org/gnu/guix/bootstrap/i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "http://alpha.gnu.org/gnu/guix/bootstrap/i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "ftp://alpha.gnu.org/gnu/guix/bootstrap/i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "http://www.fdn.fr/~lcourtes/software/guix/packages/i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "http://flashner.co.il/guix/bootstrap/i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" "http://lilypond.org/janneke/guix//i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz" ]; hash = "sha256-Gs2Pg+J9L6wxGlynjpvxGpoWOLgkaYcNXIVMTnr6omo="; name = "linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/a6j3i7qwd5yly5k92ljxzcaxp25ffxp9-linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
