# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/openjdk/jdk25u"; rev = "refs/tags/jdk-25-ga"; hash = "sha256-5kQ7xPyWGk/weVYVVNEFPUF1HspfisqcPHA+DM6Q35c="; name = "openjdk-25-checkout"; fetchSubmodules = false; }
