# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-libredox-0.1.3.tar.gz/sha256/139602gzgs0k91zb7dvgj1qh4ynb8g1lbxsswdim18hcb6ykgzy0" "https://crates.io/api/v1/crates/libredox/0.1.3/download" ]; hash = "sha256-wP83vVkMolBj41r3RcNDy3oCcZBvt7N+SBPo958AJo0="; name = "rust-libredox-0.1.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/d5396wxx5i9hns96q9n3mzzswhlqzapp-rust-libredox-0.1.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
