# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "nss-certs-for-test-3.101.4";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import''; path = ./../sources/h0m3ix02ngm6hwzwbhs4c9wqfkixvh3a-m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import; }}"
      "-C"
      "${(import ../store/anjd4i5mspyb5xv02lnv50vpzv8qgihb-module-import-compiled.nix).out}"
      "${builtins.path { name = ''nss-certs-for-test-3.101.4-builder''; path = ./../sources/4saa0gb5ks7nkf9hwgbq9rhjz0smsvq8-nss-certs-for-test-3.101.4-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "nss-certs-for-test-3.101.4-builder"; path = ./../sources/4saa0gb5ks7nkf9hwgbq9rhjz0smsvq8-nss-certs-for-test-3.101.4-builder; })
      (builtins.path { name = "m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import"; path = ./../sources/h0m3ix02ngm6hwzwbhs4c9wqfkixvh3a-m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/c5fl9qgs8k7rmx91743nqh95p1zxknyl-nss-certs-3.101.4.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/2d0g39s39s20h033wnc2n0lga3gkaxmq-nss-certs-for-test-3.101.4.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
