# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/mes-0.25.1.tar.gz/sha256/03np6h4qx94givjdvq2rmhvab38y5f91254n0avg4vq2j0cx78in" "https://ftp.gnu.org/gnu/mes/mes-0.25.1.tar.gz" "https://lilypond.org/janneke/mes/mes-0.25.1.tar.gz" ]; hash = "sha256-NqLTGZACb/K2ApYUEZIrHo2lNqxZ4N3kjo+kjgk01w4="; name = "mes-0.25.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/7bkkfbhmf10b80j5z87yaawabgsmwpq8-mes-0.25.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
