# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "module-import-compiled";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "${builtins.path { name = ''compile-modules''; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; }}"
    ];
    srcs = [
      (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
      (builtins.path { name = "build-utils.scm"; path = ./../sources/mcpxrl5ql7qyib48qn6g235balyhz7ym-build-utils.scm; })
      (builtins.path { name = "compile-modules"; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; })
    ];
    GUILE_WARN_DEPRECATED = "no";
    extensions = "";
    "module count" = "4";
    modules = "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}";
    "optimization level" = "1";
    preferLocalBuild = "1";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/2kd9jyc2vv8sr5pskw36f2k1z9p3hkd1-module-import-compiled.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
