# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-mime-guess-2.0.5.tar.gz/sha256/03jmg3yx6j39mg0kayf7w4a886dl3j15y8zs119zw01ccy74zi7p" "https://crates.io/api/v1/crates/mime_guess/2.0.5/download" ]; hash = "sha256-98RPjmcsAP5TCPojX4IctBmEFOHHeTXBq2lI0/14VQ4="; name = "rust-mime-guess-2.0.5.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/1hgmh1xmviwfj82i9q92kc02kw0s6pd8-rust-mime-guess-2.0.5.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
