# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "e2fsprogs-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''e2fsprogs-runtime-env-builder''; path = ./../sources/8m96galzfrfqbnbmppscb723r4dw9a2w-e2fsprogs-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "e2fsprogs-runtime-env-builder"; path = ./../sources/8m96galzfrfqbnbmppscb723r4dw9a2w-e2fsprogs-runtime-env-builder; })
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/nm3wp8jmkn069mnid5l6jndk2nv5dyg7-e2fsprogs-1.47.2.nix).out} ${(import ../store/3j907z1fvrbi8idqhx4vsp6i9c54xlj8-util-linux-2.40.4.nix).lib}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/2ybxm4mcl0azkillg6n9crmw7wxlqdp6-e2fsprogs-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
