# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-033/sha256/1qm2aad9mf2xah6xwchga7s5pk3v308mrv9lgh50d65d236ccgh1" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-033" ]; hash = "sha256-AT7GzBCtmAYKfDTtXBEYe8xb9FEPMt4NVF24mppSouI="; name = "bash52-033"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/8f49nkf0ym3k4jq1f7i7pn5qx3xcn6kk-bash52-033.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
