# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-crossbeam-utils-0.8.21.tar.gz/sha256/0a3aa2bmc8q35fb67432w16wvi54sfmb69rk9h5bhd18vw0c99fh" "https://crates.io/api/v1/crates/crossbeam-utils/0.8.21/download" ]; hash = "sha256-0KXEAN8oNLgKTDMns6rTpMTNTeBikGOWKwMjVpdQaig="; name = "rust-crossbeam-utils-0.8.21.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/2yq8q86lf55cfb844cnpy02v6cndw45r-rust-crossbeam-utils-0.8.21.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
