# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-percent-encoding-2.3.1.tar.gz/sha256/0gi8wgx0dcy8rnv1kywdv98lwcx67hz0a0zwpib5v2i08r88y573" "https://crates.io/api/v1/crates/percent-encoding/2.3.1/download" ]; hash = "sha256-4xSPUEYgil1WvPwDBT48pjNOUdqN+xm2zcizBvrjKD4="; name = "rust-percent-encoding-2.3.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/z400qqwg68fmhgpjvwb0lw8zirqdkbcp-rust-percent-encoding-2.3.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
