# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-lock-api-0.4.12.tar.gz/sha256/05qvxa6g27yyva25a5ghsg85apdxkvr77yhkyhapj6r8vnf8pbq7" "https://crates.io/api/v1/crates/lock_api/0.4.12/download" ]; hash = "sha256-B6+LnN0oG3kV9BP6c/KevV1V0NPwFVWE2t4f8YzqGxc="; name = "rust-lock-api-0.4.12.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/n86l0qj509aj0c5kkaqg2f1qa8bn891a-rust-lock-api-0.4.12.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
