# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-jpeg-decoder-0.3.1.tar.gz/sha256/1c1k53svpdyfhibkmm0ir5w0v3qmcmca8xr8vnnmizwf6pdagm7m" "https://crates.io/api/v1/crates/jpeg-decoder/0.3.1/download" ]; hash = "sha256-9dSn2jWO/1it3Sh3pFhlFY8NeMkR1DpXhM63u/UoM7A="; name = "rust-jpeg-decoder-0.3.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/8din8n7r19m4f8xv36hn2wd8w4b9g189-rust-jpeg-decoder-0.3.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
