# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-zerocopy-derive-0.7.35.tar.gz/sha256/0gnf2ap2y92nwdalzz3x7142f2b83sni66l39vxp2ijd6j080kzs" "https://crates.io/api/v1/crates/zerocopy-derive/0.7.35/download" ]; hash = "sha256-+k+AgDRNRnH7ToMaE60eaAknSDh9/E9V41YkL64Szj4="; name = "rust-zerocopy-derive-0.7.35.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/iqkjc5rh3r9wbbmc6j6snfpz0zn7gbdf-rust-zerocopy-derive-0.7.35.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
