# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "ecj-javac-wrapper-3.2.2";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/jsdjm29sg257a6g0mmk32s1i30r4xpi8-module-import-compiled.nix).out}"
      "${builtins.path { name = ''ecj-javac-wrapper-3.2.2-builder''; path = ./../sources/0h34mcw25pj2ck64hm4v1avyl4ycf9yr-ecj-javac-wrapper-3.2.2-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
      (builtins.path { name = "ecj-javac-wrapper-3.2.2-builder"; path = ./../sources/0h34mcw25pj2ck64hm4v1avyl4ycf9yr-ecj-javac-wrapper-3.2.2-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/fiy6ja1w4db9p228fdr68s340a81wvym-libgc-8.2.8.nix).out} ${(import ../store/j3d2rnc5shrn70srpima5iag6ll75by8-classpath-0.93.nix).out} ${(import ../store/1qkd424n7qnywd1bdrgg9pfaam7kmm8i-jamvm-1.5.1.nix).out} ${(import ../store/pd7y74psrbx55pj31gm6cizrjgfv770z-guile-3.0.9.nix).out} ${(import ../store/i9gc4fc5s4khbh5pmq5zm1y7c3lspj5y-libunistring-1.3.nix).out} ${(import ../store/mi7lshdwsgip7m2hiq0rihxgnj4hx9h1-ecj-bootstrap-3.2.2.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/3y1ab88ams8qwfgcbm7a4xwi84krf6d6-ecj-javac-wrapper-3.2.2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
