# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/icedtea-3.19.0.tar.xz/sha256/1cmms7cb2sav3ywc36ynqmybzx73sl279rm6j8i5nqrmp98ixmpf" "http://icedtea.wildebeest.org/download/source/icedtea-3.19.0.tar.xz" ]; hash = "sha256-7tYeUbo1Y1sikqbmdATV4/S/fMXWm8G4H1tpsdjRtbI="; name = "icedtea-3.19.0.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/2ilgbjm7jimskaixwzcvjpa3ia4y5b4k-icedtea-3.19.0.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
