# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "gawk-mesboot-3.1.8";
    system = "x86_64-linux";
    builder = "${(import ../store/ahkdlnqj5180w9m1bi8wiqccmqvvy1a3-guile-bootstrap-2.0.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
      "-C"
      "${(import ../store/0f46dz812m1jg4kg7bhsrrza3ll6m6da-module-import-compiled.nix).out}"
      "${builtins.path { name = ''gawk-mesboot-3.1.8-builder''; path = ./../sources/m85xsiwhvr0cjbbpjpx4rnqy2rac5vhl-gawk-mesboot-3.1.8-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
      (builtins.path { name = "gawk-mesboot-3.1.8-builder"; path = ./../sources/m85xsiwhvr0cjbbpjpx4rnqy2rac5vhl-gawk-mesboot-3.1.8-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/4zw3hb9xg5aakd522izgf1rd8svw81cc-gawk-3.1.8.tar.gz.nix).out} ${(import ../store/zrk9hfb7aqjcmsclavjlp178dbchgb5v-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/0mpc5xnckc71c6rmzj3a8lv3hjr9da7p-patch-mesboot-2.5.9.nix).out} ${(import ../store/r7j55m51ng3sqnla2pgza8zp5bckb81j-gash-utils-boot-0.2.0.nix).out} ${(import ../store/0in0jhcc2nr1n850dzai0y8abcprclfm-bootar-1b.nix).out} ${(import ../store/j3j0dsmpdwgkqgs5ig59siq60yrmsrrz-gcc-mesboot1-4.6.4.nix).out} ${(import ../store/zsw49syhanpybwm0w67419mgm40jrl0w-gzip-mesboot-1.2.4.nix).out} ${(import ../store/garxzrhvi062xdhw8575k8fzilk1gp6m-make-mesboot-3.82.nix).out} ${(import ../store/r1x90z4v304kr98zn524xkqc10inf5hs-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/lz93bz4x8x28lrwaafkjx6qvyygqi5fp-binutils-mesboot1-2.20.1a.nix).out} ${(import ../store/lld0vzxp72q2ngwkxnmpps8bgq05bcnm-gash-boot-0.3.1.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/4x0aqp37paxqbdf2d4drk46lllmfzds3-gawk-mesboot-3.1.8.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
