# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-plain-0.2.3.tar.gz/sha256/19n1xbxb4wa7w891268bzf6cbwq4qvdb86bik1z129qb0xnnnndl" "https://crates.io/api/v1/crates/plain/0.2.3/download" ]; hash = "sha256-tFlrbQcLJxF+mHEZtNrGBPPFjPsLGRES4kdxsvrqwaY="; name = "rust-plain-0.2.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/kfz3hd2fgczyp1489slkqvw635hksgpj-rust-plain-0.2.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
