# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/llvm/llvm-project"; rev = "refs/tags/llvmorg-18.1.8"; hash = "sha256-iiZKMRo/WxJaBXct9GdAcAT3cz9d9pnAcO1mmR6oPNE="; name = "llvm-project-18.1.8-checkout"; guixHash = "fyr5ylmwlnmb31vd6zykzzsj0damgxf9"; fetchSubmodules = false; }
