# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-zerovec-derive-0.10.3.tar.gz/sha256/1ik322dys6wnap5d3gcsn09azmssq466xryn5czfm13mn7gsdbvf" "https://crates.io/api/v1/crates/zerovec-derive/0.10.3/download" ]; hash = "sha256-bq+m37F1hOo+K9bnbgzBWtevErCavdHKVZYb7ZsQY8Y="; name = "rust-zerovec-derive-0.10.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/p46pmzsxdycbn43mkrnmhdnsz2l88a9h-rust-zerovec-derive-0.10.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
