# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "guile-wisp-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''guile-wisp-runtime-env-builder''; path = ./../sources/3gcj0p606czjrm158j017h4scijhk4kh-guile-wisp-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "guile-wisp-runtime-env-builder"; path = ./../sources/3gcj0p606czjrm158j017h4scijhk4kh-guile-wisp-runtime-env-builder; })
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/jzw12fkdy28sjxx8q1ng62ka354ss00l-guile-wisp-1.0.12.nix).out} ${(import ../store/fiy6ja1w4db9p228fdr68s340a81wvym-libgc-8.2.8.nix).out} ${(import ../store/pd7y74psrbx55pj31gm6cizrjgfv770z-guile-3.0.9.nix).out} ${(import ../store/i9gc4fc5s4khbh5pmq5zm1y7c3lspj5y-libunistring-1.3.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/615ncxgfqllc7gmyhccm4y3xpbhmwwzy-guile-wisp-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
