# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/certdata2pem.c/sha256/1rywp29q4l1cs2baplkbcravxqs4kw2cys4yifhfznbc210pskq6" "https://raw.githubusercontent.com/sabotage-linux/sabotage/4c576f350f44186d439179f63d5be19f710a73f5/KEEP/certdata2pem.c" ]; hash = "sha256-Bk99QRBs2e+gi55ozwSfROO+VWZr0quW0CxQgpO43Oc="; name = "certdata2pem.c"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/lczdw7nsh2fpdlcilj5y8px3bp86p4fx-certdata2pem.c.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
