# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/readline82-006/sha256/18gmh6y3klh0vv28cyqz4is3rlb32pl7f1kf5r482kfjq3w5zd67" "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-006" ]; hash = "sha256-x7Rf+MDSTYFILm4Gd+gVY9E8dCQfe4bE3gDSObyB9aE="; name = "readline82-006"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/habmpzw3qlmz87f3fx1505mzkx0wy9g4-readline82-006.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
