# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "openjdk-9.181-checkout";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/jsdjm29sg257a6g0mmk32s1i30r4xpi8-module-import-compiled.nix).out}"
      "${builtins.path { name = ''openjdk-9.181-checkout-builder''; path = ./../sources/6z7fdnvykplvn41znqf5lx8wa11rxxj4-openjdk-9.181-checkout-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "openjdk-9-jar-reproducibility.patch"; path = ./../sources/sx4p81xg35qpds86r1vxy2z3shkzgdyg-openjdk-9-jar-reproducibility.patch; })
      (builtins.path { name = "openjdk-9-module2-reproducibility.patch"; path = ./../sources/608wl6h3aqhpz12fnmn01x7gxnwapblb-openjdk-9-module2-reproducibility.patch; })
      (builtins.path { name = "openjdk-9-module3-reproducibility.patch"; path = ./../sources/xi83c5p0cqvswilk80s8m2zsfgp6dz6k-openjdk-9-module3-reproducibility.patch; })
      (builtins.path { name = "openjdk-9-module-reproducibility.patch"; path = ./../sources/mgvz078ylkrzdh48xv37is71vp38rm51-openjdk-9-module-reproducibility.patch; })
      (builtins.path { name = "openjdk-currency-time-bomb.patch"; path = ./../sources/iszjkfv9dwsd6qv92r20hk3hmp563aq1-openjdk-currency-time-bomb.patch; })
      (builtins.path { name = "openjdk-9-setsignalhandler.patch"; path = ./../sources/az0cs12s4f8y5dvdj0ir6gizz2zrvrkc-openjdk-9-setsignalhandler.patch; })
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
      (builtins.path { name = "openjdk-9-classlist-reproducibility.patch"; path = ./../sources/080asdkpd11dwshfnj0iifzk4mkwx3vn-openjdk-9-classlist-reproducibility.patch; })
      (builtins.path { name = "openjdk-9-pointer-comparison.patch"; path = ./../sources/npsm7ym0b7w97b25i1qx3s8ryclbbwc9-openjdk-9-pointer-comparison.patch; })
      (builtins.path { name = "openjdk-9.181-checkout-builder"; path = ./../sources/6z7fdnvykplvn41znqf5lx8wa11rxxj4-openjdk-9.181-checkout-builder; })
      (builtins.path { name = "openjdk-9-idlj-reproducibility.patch"; path = ./../sources/cskcll1vsrzp902f16bd4j8nyjy52sl8-openjdk-9-idlj-reproducibility.patch; })
    ];
    LC_CTYPE = "C.UTF-8";
    "guix properties" = "((type . origin) (patches . 9))";
    __phantom_deps = "${(import ../store/nrb3fvdvxkcriwqjydhgqgxqdxfh4fww-xz-5.4.5.nix).out} ${(import ../store/7sp7r2ig0qvb0wac6wlqj8p9mhg9l7fd-openjdk-9.181-checkout.nix).out} ${(import ../store/a5yvhrklbqsvr7mzpkx07ksix01y6565-tar-1.35.nix).out} ${(import ../store/s5xlhyd6fvdf1lbk92pdx54bbwz436mr-patch-2.7.6.nix).out} ${(import ../store/ymzxr25x36gi3cjp61wa7j8ic68d44vv-zstd-1.5.6.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/75zci1ka6794nf2jbvhaz9sk63cblgh8-openjdk-9.181-checkout.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
