# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/HTTP-Daemon-6.14.tar.gz/sha256/079fkcq2vdrzdf0bml52kz73n9gdv1xg0qf72c9v505v7izpwxph" "https://www.cpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.14.tar.gz" ]; hash = "sha256-8HZ+fzy7gLITE8dh8HrY7SU7zp+i0LqAaz+3LTCbLh0="; name = "HTTP-Daemon-6.14.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/czdhbvhcjcb0fkhmzp7731663yg8ds9s-HTTP-Daemon-6.14.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
