# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-035/sha256/1r8k34y82v02yfkgws17j7i53ybb74dqnwl2jjiv0av9z93hl6l2" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-035" ]; hash = "sha256-ghoKR/ppK7CjlIJyixs5a/lR4pEnaP6m8wJsgTwZE+U="; name = "bash52-035"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/hr3cxna72d1gb5bm5rismjqq8dql2yv5-bash52-035.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
