# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "module-import-compiled";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "${builtins.path { name = ''compile-modules''; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; }}"
    ];
    srcs = [
      (builtins.path { name = "build-utils.scm"; path = ./../sources/mcpxrl5ql7qyib48qn6g235balyhz7ym-build-utils.scm; })
      (builtins.path { name = "cl8nal8dnxgp6qij210a8bdahixdqn5a-module-import"; path = ./../sources/18z3cxjph9mq10pvlr3zrxfn5mi05c72-cl8nal8dnxgp6qij210a8bdahixdqn5a-module-import; })
      (builtins.path { name = "compile-modules"; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; })
    ];
    GUILE_WARN_DEPRECATED = "no";
    extensions = "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}";
    "module count" = "10";
    modules = "${builtins.path { name = ''cl8nal8dnxgp6qij210a8bdahixdqn5a-module-import''; path = ./../sources/18z3cxjph9mq10pvlr3zrxfn5mi05c72-cl8nal8dnxgp6qij210a8bdahixdqn5a-module-import; }}";
    "optimization level" = "1";
    preferLocalBuild = "1";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/7pkqxi9v86scrpb3sj4mwixmxxmhfcy0-module-import-compiled.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
