# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/hramrach/lm-sensors"; rev = "refs/tags/V3-6-2"; hash = "sha256-EmS9H3TQac6bHs2G8t1C2cQNAjN13zPoKDysny6aTFw="; name = "lm-sensors-3.6.2-checkout"; fetchSubmodules = false; }
