# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-unindent-0.1.11.tar.gz/sha256/171may3v15wzc10z64i8sahdz49d031v7424mjsifa205ml6sxp1" "https://crates.io/api/v1/crates/unindent/0.1.11/download" ]; hash = "sha256-4XZtaC1AKBe1rESQs8MALZHfoNIoEvNBYJ+XsIdXNZw="; name = "rust-unindent-0.1.11.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/46z2da42nzgk39qjii4qll0w1xyr9kad-rust-unindent-0.1.11.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
