# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/ncurses-6.2-20210619-patch.sh.bz2/sha256/1b6522cvi4066bgh9lp93q8lk93zcjjssvnw1512z447xvazy2y6" "https://invisible-mirror.net/archives/ncurses/6.2/ncurses-6.2-20210619-patch.sh.bz2" ]; hash = "sha256-xgv/1e6HkC9CCdxuraVkf6RJER7p0gTfMgaQuJkQxaw="; name = "ncurses-6.2-20210619-patch.sh.bz2"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/pqj8xixg4h4pqyzsahqqv39waspnflqc-ncurses-6.2-20210619-patch.sh.bz2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
