# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-keyring-2.3.3.tar.gz/sha256/184mshdrgghlvmlz0n7w1167yx0sa3zb82n31jk4lwcx07q8fcrn" "https://crates.io/api/v1/crates/keyring/2.3.3/download" ]; hash = "sha256-NjOH8AGdcUqmDMMKtP5QGnR/TAj8WPBp3RS+lxvUlaA="; name = "rust-keyring-2.3.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/fzwr5rizp6w8yjyb3vjrqminncirzdza-rust-keyring-2.3.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
