# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/stage0-posix-1.6.0.tar.gz/sha256/0p06wn95y6xbp2kcd81h2fm3wxvldd1qqyxgav0farl34xlzyq4j" "https://github.com/oriansj/stage0-posix/releases/download/Release_1.6.0/stage0-posix-1.6.0.tar.gz" ]; hash = "sha256-kmD/aSeDZuXAVq97jENrdHc+qhMwoMamuKsbX5LlBlw="; name = "stage0-posix-1.6.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/pr592q3dd1mid0rcr097qcajcmnqs4z8-stage0-posix-1.6.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
