# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-doc-comment-0.3.3.tar.gz/sha256/043sprsf3wl926zmck1bm7gw0jq50mb76lkpk49vasfr6ax1p97y" "https://crates.io/api/v1/crates/doc-comment/0.3.3/download" ]; hash = "sha256-/qQbujLZabUTmXdSc1YFBUvA36krTFa/EYny4XS+ehA="; name = "rust-doc-comment-0.3.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/9vyahxf0n5sx5nzj4ayfrh8iwym05rks-rust-doc-comment-0.3.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
