# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-wasm-bindgen-macro-0.2.100.tar.gz/sha256/01xls2dvzh38yj17jgrbiib1d3nyad7k2yw9s0mpklwys333zrkz" "https://crates.io/api/v1/crates/wasm-bindgen-macro/0.2.100/download" ]; hash = "sha256-f+Y/xtCe03kr0Il7MU9T3o4WVowrP3mC9GjAv5vQtAc="; name = "rust-wasm-bindgen-macro-0.2.100.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/7mh75zyxagzbh4gy1jjyrq85zmnikhz1-rust-wasm-bindgen-macro-0.2.100.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
