# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-native-tls-0.2.14.tar.gz/sha256/03hga800x8bzkp8h7frnm7yp545dwwawgmaq673vx7byk1139pl7" "https://crates.io/api/v1/crates/native-tls/0.2.14/download" ]; hash = "sha256-h940Qph+nb7HMVjVxxXnrZBy/ak2uwPRnX+hDgBSDw4="; name = "rust-native-tls-0.2.14.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/mrqim5a5z5ixf39ljrl85xpnchg90b37-rust-native-tls-0.2.14.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
