# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-bytesize-1.3.3.tar.gz/sha256/0nb645ma48nwsv1piylzcza0avjp435sl8krhyws3q18kv5ap4rf" "https://crates.io/api/v1/crates/bytesize/1.3.3/download" ]; hash = "sha256-LpOryp4o4KG5h3kiqssgV24F1Gef+njD1twiomohZlk="; name = "rust-bytesize-1.3.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/zm81jmyk7vk4v7mlvgig2w0hf90car84-rust-bytesize-1.3.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
