# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/static-binaries.tar.xz/sha256/0c533p9dhczzcsa1117gmfq3pc8w362g4mx84ik36srpr7cx2bg4" "https://ftpmirror.gnu.org/guix/bootstrap//x86_64-linux/20131110/static-binaries.tar.xz" "https://ftp.gnu.org/gnu/guix/bootstrap/x86_64-linux/20131110/static-binaries.tar.xz" "http://ftp.gnu.org/gnu/guix/bootstrap/x86_64-linux/20131110/static-binaries.tar.xz" "https://alpha.gnu.org/gnu/guix/bootstrap/x86_64-linux/20131110/static-binaries.tar.xz" "http://alpha.gnu.org/gnu/guix/bootstrap/x86_64-linux/20131110/static-binaries.tar.xz" "ftp://alpha.gnu.org/gnu/guix/bootstrap/x86_64-linux/20131110/static-binaries.tar.xz" "http://www.fdn.fr/~lcourtes/software/guix/packages/x86_64-linux/20131110/static-binaries.tar.xz" "http://flashner.co.il/guix/bootstrap/x86_64-linux/20131110/static-binaries.tar.xz" "http://lilypond.org/janneke/guix//x86_64-linux/20131110/static-binaries.tar.xz" ]; hash = "sha256-5C3R2ck3azNmJKhX8oQZHLE7sKvvhBCUZv8z2NIdozA="; name = "static-binaries.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/062dwi8akdfay0cx8s6z9hg19i2h2a7f-static-binaries.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
