# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-hashbrown-0.14.5.tar.gz/sha256/1wa1vy1xs3mp11bn3z9dv0jricgr6a2j0zkf1g19yz3vw4il89z5" "https://crates.io/api/v1/crates/hashbrown/0.14.5/download" ]; hash = "sha256-5SdEI+F7fJ/CC25+IIUy+bGYJdgt/WFXCLcO3YPfQfE="; name = "rust-hashbrown-0.14.5.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/n58r0b0l5v0qn78gr5pgs1y2pj46h5wn-rust-hashbrown-0.14.5.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
