# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/fonttools-4.59.2.tar.gz/sha256/08pgq9nrj3r81gzb6gbf5mcak0xyqrj26cw0rc5za4v1n14hfb77" "https://files.pythonhosted.org/packages/source/f/fonttools/fonttools-4.59.2.tar.gz" ]; hash = "sha256-5ywHSbBhE/ULy4AzI2TGvoOpWC1uPbP+CygPmW3C7yI="; name = "fonttools-4.59.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/v76f5ryikzy0d2v56y4mvqcc2gfcbcqv-fonttools-4.59.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
