# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/inetutils-2.5.tar.gz/sha256/0q1257ci22g2jbdiqs00mharc1lqkbibdlkhj23f3si6qjxkn17s" "https://ftp.gnu.org/gnu/inetutils/inetutils-2.5.tar.gz" ]; hash = "sha256-+gQ7u8Qm6uGGkHDStuKamAaWFawAaBzbkuIJEdkpImA="; name = "inetutils-2.5.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/2hkl8dn4jy7dmrwmfx1j0gkmsy7xf0k4-inetutils-2.5.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
