# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-cargo-platform-0.1.9.tar.gz/sha256/1sinpmqjdk3q9llbmxr0h0nyvqrif1r5qs34l000z73b024z2np3" "https://crates.io/api/v1/crates/cargo-platform/0.1.9/download" ]; hash = "sha256-41rxiQBrnA8AoGRoXHJwMePtLYAg97ooTXjMJnG9Nuo="; name = "rust-cargo-platform-0.1.9.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/kdk8mb0m6iffw1bw8djikwnqgy526czc-rust-cargo-platform-0.1.9.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
