# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/pytest-dev/pyfakefs"; rev = "refs/tags/v5.9.1"; hash = "sha256-U+5fNdxg5eA3CoPtlLMTyr5/67OO0/kWhzZnvJ5DuHU="; name = "python-pyfakefs-5.9.1-checkout"; guixHash = "srg2d248dh7qzby2hqwc5f4p5imrnl1a"; fetchSubmodules = false; }
