# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-camino-1.1.9.tar.gz/sha256/1lqszl12l1146jf8g01rvjmapif82mhzih870ln3x0dmcr4yr5lb" "https://crates.io/api/v1/crates/camino/1.1.9/download" ]; hash = "sha256-i5bsSWa1gT4sBQfB+GEVyMWrqtw5gIecNCQEKgL9GtM="; name = "rust-camino-1.1.9.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/hs1xir6c9w3q3ila9hssddsn2vd32rlm-rust-camino-1.1.9.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
