# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-pyo3-build-config-0.23.5.tar.gz/sha256/1yqhw1k466k65rqvy2d4xz2shl0hzkry1xlxinciigzkdvlcpxll" "https://crates.io/api/v1/crates/pyo3-build-config/0.23.5/download" ]; hash = "sha256-lPbL6G7zvxiZjZ324PP8EFCoxe+kCb9xLmYaQ2bgEPs="; name = "rust-pyo3-build-config-0.23.5.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/l58bkg5ch8zqs7y5xzvczalx5rxhyba8-rust-pyo3-build-config-0.23.5.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
