# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/linux-libre-6.12.17-gnu.tar.xz/sha256/1j3iyivh8h9abryjqksf4k51wgwnwqy2l3zsc019bm84xmka38xm" "https://ftp.gnu.org/gnu/linux-libre/6.12.17-gnu/linux-libre-6.12.17-gnu.tar.xz" "https://linux-libre.fsfla.org/pub/linux-libre/releases/6.12.17-gnu/linux-libre-6.12.17-gnu.tar.xz" "ftp://alpha.gnu.org/gnu/guix/mirror/linux-libre-6.12.17-gnu.tar.xz" ]; hash = "sha256-taOhZu0E1ZUCYPoPKjzmlj8eyiROTyx9XipBBHf0ccg="; name = "linux-libre-6.12.17-gnu.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/xfp19rzchv4l75lqsp2clqnqbaa7a3a0-linux-libre-6.12.17-gnu.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
