# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-derive-arbitrary-1.4.1.tar.gz/sha256/000839h4mbgs65x1f8540kbjk2ifw68c4d8r5b9f7q0jv4d2qm1h" "https://crates.io/api/v1/crates/derive_arbitrary/1.4.1/download" ]; hash = "sha256-MFQsGtkS4OPSKhk1wpDhLoop1wSkIBd6MfqtSmAaCAA="; name = "rust-derive-arbitrary-1.4.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/zsr0nhlap49pmy04df94gblqva2zsbf8-rust-derive-arbitrary-1.4.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
