# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/man-db-2.12.0.tar.xz/sha256/15bak56wf99xdr1p3kaish6pkrrvhl6p2rhgzwiasr17la264nj1" "https://download.savannah.nongnu.org/releases/man-db/man-db-2.12.0.tar.xz" ]; hash = "sha256-QVpihKInZK0i/w9mcQ2FO+d5DdRRzXFDbj0lx02ZapU="; name = "man-db-2.12.0.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/i7382h57ba2b3v219k8qii76gjxk2nsf-man-db-2.12.0.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
