# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "python-wrapper-3.11.14";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/jsdjm29sg257a6g0mmk32s1i30r4xpi8-module-import-compiled.nix).out}"
      "${builtins.path { name = ''python-wrapper-3.11.14-builder''; path = ./../sources/cs75ybgqk5g4sv21g2p4shb1bpl78xrb-python-wrapper-3.11.14-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
      (builtins.path { name = "python-wrapper-3.11.14-builder"; path = ./../sources/cs75ybgqk5g4sv21g2p4shb1bpl78xrb-python-wrapper-3.11.14-builder; })
      (builtins.path { name = "sitecustomize.py"; path = ./../sources/sm310qy71q4i1s4rn0a5a29ryyiydvd4-sitecustomize.py; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/xi5jpdai7acvzssc5rqmkpalh6qvdr7b-unzip-6.0.nix).out} ${(import ../store/bsdvxhipmj95vi878dsvyp64flmhd206-bash-5.2.37.nix).out} ${(import ../store/f884y53f29999iqn72gzs5ymdxakwla1-python-3.11.14.nix).out} ${(import ../store/v3zziqgm4nykafgxbd8azhzh7kkakvd8-tzdata-2025a.nix).out} ${(import ../store/i1rnf3klc70lqwqi1mfd16aaahx4az11-zip-3.0.nix).out} ${(import ../store/q0d228ii5j87jwvp0714lvldplsri5h1-pkg-config-0.29.2.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/c6f0wpn95j605aaxpl344xaag78f460a-python-wrapper-3.11.14.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
