# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-014/sha256/09766vqqw4ffnmysm725v35qkhp1g9j4qgqag941xvq655pj9y9y" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-014" ]; hash = "sha256-PvkkbykG7x5Iego/TGR64cKJy9hFnKp9tc4RjvE25iQ="; name = "bash52-014"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/shf0kmaisjscl3vk2d0yfnd2ycgyaihx-bash52-014.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
