# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/dejavu-fonts-ttf-2.37.tar.bz2/sha256/1mqpds24wfs5cmfhj57fsfs07mji2z8812i5c4pi5pbi738s977s" "https://downloads.sourceforge.net/dejavu/dejavu/2.37/dejavu-fonts-ttf-2.37.tar.bz2" ]; hash = "sha256-+pyk0Thx3RIvYSWKgNAXUdYDtNPuFAldZUU7ToRuF9c="; name = "dejavu-fonts-ttf-2.37.tar.bz2"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/bjlam9c855k4pwz3mbb31fnbi2gwv434-dejavu-fonts-ttf-2.37.tar.bz2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
