# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/lz4/lz4"; rev = "refs/tags/v1.10.0"; hash = "sha256-/dG1n59SKBaEBg72pAWltAtVmJ2cXxlFFhP+klrkTos="; name = "lz4-1.10.0-checkout"; guixHash = "2wn6ibqfr0haw8fwhvm5bj0dxjzv9sip"; fetchSubmodules = false; }
