# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/json-glib-1.10.0.tar.xz/sha256/0yxg215gpa61sxnx05bgzbqq9dsvbawk6cfz8z0yq1k1v5k8vjhv" "https://download.gnome.org/sources/json-glib/1.10/json-glib-1.10.0.tar.xz" ]; hash = "sha256-G8qNZtlhBuzBR98xM7laW7eE8fpvFdBt18Go+0oQr3s="; name = "json-glib-1.10.0.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/8gl721h60ilacw7xvq6ndx9x6xfwjgri-json-glib-1.10.0.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
