# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "gawk-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''gawk-runtime-env-builder''; path = ./../sources/bcria19g9qwil62afrx4my8a7a9v5cc5-gawk-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
      (builtins.path { name = "gawk-runtime-env-builder"; path = ./../sources/bcria19g9qwil62afrx4my8a7a9v5cc5-gawk-runtime-env-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/bsdvxhipmj95vi878dsvyp64flmhd206-bash-5.2.37.nix).out} ${(import ../store/xxdpljkq5m5d4manz2y0bqwabfrcdqya-gawk-5.3.0.nix).out} ${(import ../store/8vr8gkbbkiicankjklfs9agi6nbzgb7h-libsigsegv-2.14.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/cms6cqbbjmy4bn454kyv7jy9843ri2bk-gawk-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
