# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-serde-derive-internals-0.29.1.tar.gz/sha256/04g7macx819vbnxhi52cx0nhxi56xlhrybgwybyy7fb9m4h6mlhq" "https://crates.io/api/v1/crates/serde_derive_internals/0.29.1/download" ]; hash = "sha256-GNJqIKlpueP98vwtnyHtpsQOLehMlAi7XTsF1Jmq5xE="; name = "rust-serde-derive-internals-0.29.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/ygqv4ksyj8ay07klj3hv6dsfjl3vk9ry-rust-serde-derive-internals-0.29.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
