# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-crc32fast-1.4.2.tar.gz/sha256/1czp7vif73b8xslr3c9yxysmh9ws2r8824qda7j47ffs9pcnjxx9" "https://crates.io/api/v1/crates/crc32fast/1.4.2/download" ]; hash = "sha256-qXdp2U3auUPkUQ0TgVAWmidYte8+sZGp7miN4+I+97M="; name = "rust-crc32fast-1.4.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/q25jnhmy2xqd1f24il6rcwrryiif5vdi-rust-crc32fast-1.4.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
