# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/snowballstemmer-2.2.0.tar.gz/sha256/1ccwy75i0f5yi1vy6fyvr1gf43ydhjani45mswm43ls7hpmnvc89" "https://files.pythonhosted.org/packages/source/s/snowballstemmer/snowballstemmer-2.2.0.tar.gz" ]; hash = "sha256-CbFt64VH00Eq17WQaJWEzQ/iXsjbO+N3iL44EMvxnLE="; name = "snowballstemmer-2.2.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/dmp1axlgbzin77616yi65jmb9fw9whz0-snowballstemmer-2.2.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
