# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-approx-0.5.1.tar.gz/sha256/1ilpv3dgd58rasslss0labarq7jawxmivk17wsh8wmkdm3q15cfa" "https://crates.io/api/v1/crates/approx/0.5.1/download" ]; hash = "sha256-yrES8KhtVo6g5ifMHWvnSh6c1VIUaE21VhmV9trYl8Y="; name = "rust-approx-0.5.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/r5a9vk171avhqkj5zhw9cfs6vpj7b844-rust-approx-0.5.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
