# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/google/brotli"; rev = "refs/tags/v1.0.9"; hash = "sha256-tFnXSXv8t3l3HX6GwWLhEtgpqz0c7Yom5U3k47pWM7o="; name = "brotli-1.0.9-checkout"; guixHash = "5qy8vwy0lm2s4hfqjp3g77q8rwqwdsja"; fetchSubmodules = false; }
