# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-inotify-sys-0.1.5.tar.gz/sha256/1syhjgvkram88my04kv03s0zwa66mdwa5v7ddja3pzwvx2sh4p70" "https://crates.io/api/v1/crates/inotify-sys/0.1.5/download" ]; hash = "sha256-4FwCteib/zuUbO3sonirxij+gR5gTwJ8RaiqPPeT0Os="; name = "rust-inotify-sys-0.1.5.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/xh6vp77gi7nh9skbbzi1y61nc41bfg6n-rust-inotify-sys-0.1.5.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
