# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/poppler-22.09.0.tar.xz/sha256/0bhyli95h3dkirjc0ibh08s4nim6rn7f38sbfzdwln8k454gga6p" "https://poppler.freedesktop.org/poppler-22.09.0.tar.xz" ]; hash = "sha256-16j3SCETWcrbd0uj4Y7NpkZLNAJwRcBkjrMNWFKkHi4="; name = "poppler-22.09.0.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/9lqg4hwmxamyjdh5041aymrw1k358w71-poppler-22.09.0.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
