# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/Reference-LAPACK/lapack/"; rev = "refs/tags/v3.12.1"; hash = "sha256-SfKsvZ07v87tFFd9bnkIEdervyX/ucLfs/TOsl08aKQ="; name = "lapack-3.12.1-checkout"; guixHash = "4456ihvnk92fbcn220vh08i3wv838i4n"; fetchSubmodules = false; }
