# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-stable-deref-trait-1.2.0.tar.gz/sha256/1lxjr8q2n534b2lhkxd6l6wcddzjvnksi58zv11f9y0jjmr15wd8" "https://crates.io/api/v1/crates/stable_deref_trait/1.2.0/download" ]; hash = "sha256-qPEScpUS+ORC2B+VqKfd8rfGuKGm9QmpWGQUKzDKstM="; name = "rust-stable-deref-trait-1.2.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/1zk1bwarrfblbza8jm7cy33qhpyrxccr-rust-stable-deref-trait-1.2.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
