# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-quote-1.0.40.tar.gz/sha256/1394cxjg6nwld82pzp2d4fp6pmaz32gai1zh9z5hvh0dawww118q" "https://crates.io/api/v1/crates/quote/1.0.40/download" ]; hash = "sha256-GIXAOVcNwA3LT/CHqJ4YX9VrriNN3H8FapRb82RnJI0="; name = "rust-quote-1.0.40.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/avf99gbpa6729agkqzpxk1b90pwm1ajg-rust-quote-1.0.40.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
