# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-crossbeam-epoch-0.9.18.tar.gz/sha256/03j2np8llwf376m3fxqx859mgp9f83hj1w34153c7a9c7i5ar0jv" "https://crates.io/api/v1/crates/crossbeam-epoch/0.9.18/download" ]; hash = "sha256-W4KsSjwsqcNGCWTwIOFALt1XU0EddzeqOcNxStG1Qg4="; name = "rust-crossbeam-epoch-0.9.18.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/v4g889cgw752w1ah1davfg2831mxfrqy-rust-crossbeam-epoch-0.9.18.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
