# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/python-dbusmock-0.30.0.tar.gz/sha256/1hanz6x76jq66ypdirga5h15zjs67kwysl6rmsf0i22dbdqrxdfv" "https://files.pythonhosted.org/packages/source/p/python-dbusmock/python-dbusmock-0.30.0.tar.gz" ]; hash = "sha256-27WecVtNiAicrtlQ7fk8RstfAizq5diuNwZLc7r5VsE="; name = "python-dbusmock-0.30.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/xpnni3hdng3bf9l2acwwp4h037ahnjji-python-dbusmock-0.30.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
