# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-futures-timer-3.0.3.tar.gz/sha256/094vw8k37djpbwv74bwf2qb7n6v6ghif4myss6smd6hgyajb127j" "https://crates.io/api/v1/crates/futures-timer/3.0.3/download" ]; hash = "sha256-8oiwpPIPmla10dpX4iJ8Zht7FhaOL3I2X1e2MybimyQ="; name = "rust-futures-timer-3.0.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/1kxbrpzp9y0qggcngkf5s0427j5888hb-rust-futures-timer-3.0.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
