# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/zipp-3.23.0.tar.gz/sha256/0rj182i2d7d2bz067zrk39s19j09xsxkzprl82fqql8ji9c5fwd0" "https://files.pythonhosted.org/packages/source/z/zipp/zipp-3.23.0.tar.gz" ]; hash = "sha256-oHFXWIoSUYydQDTfP7vuCcgUdBoz/2PAX6KdJqJAQWY="; name = "zipp-3.23.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/brw7rgzd3fiaw17kg2yl3fj9jnj7r1lb-zipp-3.23.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
