# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-oorandom-11.1.5.tar.gz/sha256/07mlf13z453fq01qff38big1lh83j8l6aaglf63ksqzzqxc0yyfn" "https://crates.io/api/v1/crates/oorandom/11.1.5/download" ]; hash = "sha256-1nkPWMf/Yz2HcfQpZSiSA0EaXlxoOIcDwG4U8kdwtB4="; name = "rust-oorandom-11.1.5.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/yaf9lnlqp4jgdy5szqqd0m5a3dr4c6dv-rust-oorandom-11.1.5.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
