# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/Test-Fatal-0.016.tar.gz/sha256/13vqdyk95y89msk1r8g1vp1jw6rzkl1y76lprnw3085sy8qd90vj" "https://www.cpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.016.tar.gz" ]; hash = "sha256-coPUMPK6IDC4zZea4wOdPxsuw93hoRymrgn5kqZveI8="; name = "Test-Fatal-0.016.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/dqp13arq3hj3b4m4a03zb3py8kjanl6a-Test-Fatal-0.016.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
