# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-gdk-pixbuf-0.19.8.tar.gz/sha256/16c6kznkh3vi82843ays8awdm37fwjd1fblv6g3h64824shsnkk2" "https://crates.io/api/v1/crates/gdk-pixbuf/0.19.8/download" ]; hash = "sha256-Yk6roSYCEQPHM5suF5rk7ozauELaq0GQQHEPOO2fhpk="; name = "rust-gdk-pixbuf-0.19.8.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/dky89h4vgaarzlsgbqn7z68nbwbhzn8s-rust-gdk-pixbuf-0.19.8.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
