# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/jdk.tar.bz2/sha256/0d1mca38ksxvdskp9im3pp7fdijhj1n3lwq9w13r9s4v3qyskgdd" "http://icedtea.classpath.org/download/drops/icedtea7/2.6.13/jdk.tar.bz2" ]; hash = "sha256-rb2pPR6b6JRH4AlzOmyQUMbmzr2jxnSnbrvriYZiNTQ="; name = "jdk.tar.bz2"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/rxnfbr8mvp7f018m5v01gdnkpfzf1n2g-jdk.tar.bz2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
