# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libjpeg-turbo-2.1.4.tar.gz/sha256/0arl61ici38ann5xjidwdzkhmjdp1r95x4x4zinnh4qs2fhjdvfk" "https://downloads.sourceforge.net/libjpeg-turbo/2.1.4/libjpeg-turbo-2.1.4.tar.gz" ]; hash = "sha256-0+0moRMaE2ht/KSTXlIOt8kK52+8RdmLtQqNyGIwNCs="; name = "libjpeg-turbo-2.1.4.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/lk7ayk9qjdmfc0956p2kbiq7l6q4pkph-libjpeg-turbo-2.1.4.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
