# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libtirpc-1.3.1.tar.bz2/sha256/05zf16ilwwkzv4cccaac32nssrj3rg444n9pskiwbgk6y359an14" "https://downloads.sourceforge.net/libtirpc/libtirpc/1.3.1/libtirpc-1.3.1.tar.bz2" ]; hash = "sha256-JFiVyvBmvsXj1DdZQsjLQ2atrRhMKcYY2X9yTqMJ7hc="; name = "libtirpc-1.3.1.tar.bz2"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/5if6zhj5k456nfnwhd6793f2xhwr7sgj-libtirpc-1.3.1.tar.bz2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
