# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-python3-dll-a-0.2.13.tar.gz/sha256/1vfl9qpx1mj4fdzijkx1yb8z91gilc725l1ajj9r9kw8l8kl5zj9" "https://crates.io/api/v1/crates/python3-dll-a/0.2.13/download" ]; hash = "sha256-Sf5CJ6KIz5STlCrQIg6j8YX00fKhTxl/c0TW0C9O1O0="; name = "rust-python3-dll-a-0.2.13.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/38apc0c1nkhm0gp1ds33acynazcf3dw4-rust-python3-dll-a-0.2.13.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
