# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-equivalent-1.0.2.tar.gz/sha256/03swzqznragy8n0x31lqc78g2af054jwivp7lkrbrc0khz74lyl7" "https://crates.io/api/v1/crates/equivalent/1.0.2/download" ]; hash = "sha256-h3pKzocTsLzypOfuyCUpwCnx0GGYhtGBRf6pbD/+XA8="; name = "rust-equivalent-1.0.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/z1dgmd8hs20ap7gglyhgmr7z0h0xn54l-rust-equivalent-1.0.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
