# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-wasm-bindgen-test-macro-0.3.50.tar.gz/sha256/16znd6wz79v2i3b2sf5n4ld2kcci8br3wcx7z5c9c07sqln09m8p" "https://crates.io/api/v1/crates/wasm-bindgen-test-macro/0.3.50/download" ]; hash = "sha256-F9UELMX6AJZY+aczPvJCkbEpGiW2OC3WiGKn87lp9ps="; name = "rust-wasm-bindgen-test-macro-0.3.50.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/nyg42abp998vrgf4dgzhfcafjza9i51s-rust-wasm-bindgen-test-macro-0.3.50.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
