# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libntlm-1.6.tar.gz/sha256/08b83nss16jsn213j326yhn1vnrz10k15fwq6jm5b1vdn23nndzj" "https://www.nongnu.org/libntlm/releases/libntlm-1.6.tar.gz" ]; hash = "sha256-8jdrh7Bth1WqNJi7EiYIP9sdLPRGDDmCsFqaoLUdaCE="; name = "libntlm-1.6.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/ms7xxppm8xa6n1ry3c1yhhlpwjvp8wf4-libntlm-1.6.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
