# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-cairo-rs-0.19.4.tar.gz/sha256/0qp5rixgipdj9d8yd5458hzfxam1rgpzcxi90vq6q0v91r6jmb5j" "https://crates.io/api/v1/crates/cairo-rs/0.19.4/download" ]; hash = "sha256-sqwqTQ5pA2zwBil29u/LoaruPkSFlOZRS7Ld+HrM5WI="; name = "rust-cairo-rs-0.19.4.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/5ijw9m2q6dz8g8x1rlmsmsgmfbzmr58c-rust-cairo-rs-0.19.4.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
