# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bootar-1b.ses/sha256/0cf5vj5yxfvkgzvjvh2l7b2nz5ji5l534n9g4mfp8f5jsjqdrqjc" "https://ftp.gnu.org/gnu/guix/mirror/bootar-1b.ses" "https://files.ngyro.com/bootar/bootar-1b.ses" ]; hash = "sha256-TOLcsNSyOHRdJS9ZMgotUZZvxTpUwC33f3O77ovcxTE="; name = "bootar-1b.ses"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/ls9zvg7k09ah1fiil86j99dihnb9ayyq-bootar-1b.ses.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
