# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "texlive-source-2025.2-checkout";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/jsdjm29sg257a6g0mmk32s1i30r4xpi8-module-import-compiled.nix).out}"
      "${builtins.path { name = ''texlive-source-2025.2-checkout-builder''; path = ./../sources/mbp3wjri7mvnfs1gy0rj7gxhhk70dnmx-texlive-source-2025.2-checkout-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "texlive-source-2025.2-checkout-builder"; path = ./../sources/mbp3wjri7mvnfs1gy0rj7gxhhk70dnmx-texlive-source-2025.2-checkout-builder; })
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    "guix properties" = "((type . origin) (patches . 0))";
    __phantom_deps = "${(import ../store/nrb3fvdvxkcriwqjydhgqgxqdxfh4fww-xz-5.4.5.nix).out} ${(import ../store/a5yvhrklbqsvr7mzpkx07ksix01y6565-tar-1.35.nix).out} ${(import ../store/s5xlhyd6fvdf1lbk92pdx54bbwz436mr-patch-2.7.6.nix).out} ${(import ../store/6vjwxkri9qkb8wg3adyvjihj6ghvcxzf-texlive-source-2025.2-checkout.nix).out} ${(import ../store/ymzxr25x36gi3cjp61wa7j8ic68d44vv-zstd-1.5.6.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/hqrjhvack4n7xabnplicclfy5is2ial3-texlive-source-2025.2-checkout.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
