# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-safe-arch-0.7.4.tar.gz/sha256/08sk47n1kcm5w2di6bpgi2hsw8r2caz2230pwqvbdqfv5pl2vc4n" "https://crates.io/api/v1/crates/safe_arch/0.7.4/download" ]; hash = "sha256-lrAt6C3b4bY25hcMIb5iIiOuoYjvLhOb4KWyGewhUyM="; name = "rust-safe-arch-0.7.4.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/z7pc1wly841nsvb9v5gg14pglkpxbkpz-rust-safe-arch-0.7.4.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
