# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/linux-6.12.62.tar.xz/sha256/04rcnr7bgrqqfj62l31mxx553bjdalr5f46xjbcmvawgmj2wdqhk" "https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.12.62.tar.xz" ]; hash = "sha256-E+LGhayPq13Zkt0QVzJVTa5RSu81DCqMdBjnt062LBM="; name = "linux-6.12.62.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/9i5x8nq8jwvg3g52r9phgn72ck6dcc1b-linux-6.12.62.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
