# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/regebro/tzlocal"; rev = "refs/tags/5.2"; hash = "sha256-x9f709Kb3r1AiwTAQV1cvHhzUpZHKaWsRII77Uoc6qo="; name = "python-tzlocal-5.2-checkout"; guixHash = "48n2a6f7llzx1lgyb0q19rrvjmm2aj05"; fetchSubmodules = false; }
