# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/types_setuptools-80.9.0.20250529.tar.gz/sha256/149w6lg8n56k50n08jx450ni9frs2hzbv729sv48c8ds1jx8iq3r" "https://files.pythonhosted.org/packages/source/t/types_setuptools/types_setuptools-80.9.0.20250529.tar.gz" ]; hash = "sha256-eeCIugy6IYbI1kmcvT4UOrsULSikSwQsKNMUix41PJE="; name = "types_setuptools-80.9.0.20250529.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/7n1gry0rp0vx9rbvwj5n44rzjdb927gx-types_setuptools-80.9.0.20250529.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
