# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/jaraco_test-5.5.1.tar.gz/sha256/0xfkly5w4i4npi4pq1g32y8q8iijkq4pfcfs8wcjhfn4amj6212c" "https://files.pythonhosted.org/packages/source/j/jaraco_test/jaraco_test-5.5.1.tar.gz" ]; hash = "sha256-TARhZFXEOigZR9oxdwmeMkaEkRfjBXxJvJZEwoun03U="; name = "jaraco_test-5.5.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/v0jjzi563rp817h8jj9r34ahrr3fjskv-jaraco_test-5.5.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
