# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/xcb-proto-1.17.0.tar.xz/sha256/130lc8jx43s83496nc8jn47zixjcp4abgsz69pvrjiqg279aq6rc" "https://xcb.freedesktop.org/dist/xcb-proto-1.17.0.tar.xz" ]; hash = "sha256-LBus0hEPR5n3TebrtxS5TPb4D7ESMWsSGUgP0iViFIw="; name = "xcb-proto-1.17.0.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/hkwf075izgb4wr0lpl0rgvndrsk2mc1j-xcb-proto-1.17.0.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
