# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "docbkx412.zip";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/jsdjm29sg257a6g0mmk32s1i30r4xpi8-module-import-compiled.nix).out}"
      "${builtins.path { name = ''docbkx412.zip-builder''; path = ./../sources/hqc7dq90dnji5mk3a62cg0g1xglv4nrh-docbkx412.zip-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "docbkx412.zip-builder"; path = ./../sources/hqc7dq90dnji5mk3a62cg0g1xglv4nrh-docbkx412.zip-builder; })
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/xi5jpdai7acvzssc5rqmkpalh6qvdr7b-unzip-6.0.nix).out} ${(import ../store/p0hi26a3gc887k1lkhxn8j0hn3xi79j7-zipbomb-docbkx412.zip.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/iqaav6lsmc9vszjqs2w51wsbrpyzkxcf-docbkx412.zip.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
