# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-mime-0.3.17.tar.gz/sha256/16hkibgvb9klh0w0jk5crr5xv90l3wlf77ggymzjmvl1818vnxv8" "https://crates.io/api/v1/crates/mime/0.3.17/download" ]; hash = "sha256-aHe7UUCB7ip/9e+d4ygfFKTdS86sTAk4gHSmtd+KE5o="; name = "rust-mime-0.3.17.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/d68kmj4akbbvi7kprfnhs3ilbnbkr19h-rust-mime-0.3.17.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
