# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "gcc-mesboot1-4.6.4";
    system = "x86_64-linux";
    builder = "${(import ../store/ahkdlnqj5180w9m1bi8wiqccmqvvy1a3-guile-bootstrap-2.0.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
      "-C"
      "${(import ../store/0f46dz812m1jg4kg7bhsrrza3ll6m6da-module-import-compiled.nix).out}"
      "${builtins.path { name = ''gcc-mesboot1-4.6.4-builder''; path = ./../sources/b6qprkv02vqawsacsazk75c561m8qsj3-gcc-mesboot1-4.6.4-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
      (builtins.path { name = "gcc-boot-4.6.4.patch"; path = ./../sources/vvs3n0s0z06w3pmim66c1gbgngj1w34i-gcc-boot-4.6.4.patch; })
      (builtins.path { name = "gcc-mesboot1-4.6.4-builder"; path = ./../sources/b6qprkv02vqawsacsazk75c561m8qsj3-gcc-mesboot1-4.6.4-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/4a1pv7pgnbvzhk768i2lfw3azlygawqz-gcc-g++-4.6.4.tar.gz.nix).out} ${(import ../store/69z84pzjkwms0cxrmjrnrzqan901pa6f-gcc-core-4.6.4.tar.gz.nix).out} ${(import ../store/7rsy9kwa1jvsil21avgqgfnjfvsc4snq-gmp-4.3.2.tar.gz.nix).out} ${(import ../store/zrk9hfb7aqjcmsclavjlp178dbchgb5v-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/0mpc5xnckc71c6rmzj3a8lv3hjr9da7p-patch-mesboot-2.5.9.nix).out} ${(import ../store/r7j55m51ng3sqnla2pgza8zp5bckb81j-gash-utils-boot-0.2.0.nix).out} ${(import ../store/0in0jhcc2nr1n850dzai0y8abcprclfm-bootar-1b.nix).out} ${(import ../store/zsw49syhanpybwm0w67419mgm40jrl0w-gzip-mesboot-1.2.4.nix).out} ${(import ../store/z70hrcdvdx9gy9wfpv81r5nn7l2j83a0-gcc-mesboot0-2.95.3.nix).out} ${(import ../store/garxzrhvi062xdhw8575k8fzilk1gp6m-make-mesboot-3.82.nix).out} ${(import ../store/r1x90z4v304kr98zn524xkqc10inf5hs-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/ld9r1azyxbiqcp0frrndjv9ih48icif3-mpfr-2.4.2.tar.gz.nix).out} ${(import ../store/lz93bz4x8x28lrwaafkjx6qvyygqi5fp-binutils-mesboot1-2.20.1a.nix).out} ${(import ../store/lld0vzxp72q2ngwkxnmpps8bgq05bcnm-gash-boot-0.3.1.nix).out} ${(import ../store/x1j4kyqq4x7lqrjnif1mkdqr06blr3i4-mpc-1.0.3.tar.gz.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/j3j0dsmpdwgkqgs5ig59siq60yrmsrrz-gcc-mesboot1-4.6.4.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
