# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "iputils-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''iputils-runtime-env-builder''; path = ./../sources/knfqjkcf87bvn583jp5zpv8bfj2gn7s1-iputils-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
      (builtins.path { name = "iputils-runtime-env-builder"; path = ./../sources/knfqjkcf87bvn583jp5zpv8bfj2gn7s1-iputils-runtime-env-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/33lnh66p45j3m89p4yzzq5i6im6v203w-libcap-2.64.nix).out} ${(import ../store/vcppqfyhgpjv5xx33r7l629xcxpha1in-libidn2-2.3.7.nix).out} ${(import ../store/24yx1afrpp8fnxs55ls71jng1wlkh333-iputils-20250605.nix).out} ${(import ../store/nlsdhjjbagg3sz44g347crh11zpk795v-openssl-3.0.8.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/j5ii8pid7r5cmk8s7rvyimrascdzvkih-iputils-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
