# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "inetutils-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''inetutils-runtime-env-builder''; path = ./../sources/7rq00rjxhk41wq1rqdwjllpw2j19vqyb-inetutils-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
      (builtins.path { name = "inetutils-runtime-env-builder"; path = ./../sources/7rq00rjxhk41wq1rqdwjllpw2j19vqyb-inetutils-runtime-env-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/xvi44mkzj546wvirh3d10w35bh8w0sgd-inetutils-2.5.nix).out} ${(import ../store/c2irpm67j1m0m67issl4c7gj1g4s4fym-ncurses-6.2.20210619.nix).out} ${(import ../store/r3hlir82ik8f8cr20836356aipddp0r1-libxcrypt-4.4.38.nix).out} ${(import ../store/03b6ilqaj81ygb47z5mz0ms90ahy5y6p-shadow-4.13.nix).out} ${(import ../store/4jy803h9d53cmdqmpv1s2a748z7kgljf-readline-8.2.13.nix).out} ${(import ../store/yikij9h9vf6mxzlnl11bpf6aikxcvl4b-coreutils-9.1.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/j6dngydk5bfqwa4q0ph523ix08239viz-inetutils-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
