# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-zerocopy-derive-0.8.24.tar.gz/sha256/1gk9047pbq1yjj2jyiv0s37nqc53maqbmhcsjp6lhi2w7kvai5m9" "https://crates.io/api/v1/crates/zerocopy-derive/0.8.24/download" ]; hash = "sha256-qZao9jxcREjNlZrBurCqozBsz9BgRy+FlD7gdQ8Bab4="; name = "rust-zerocopy-derive-0.8.24.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/w20d0s7vn8cdgzcvkqzcj76p26sd5q94-rust-zerocopy-derive-0.8.24.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
