# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-platform-info-2.0.5.tar.gz/sha256/06j5v6hg914lbdr732jfx5syx703l5qwy1qk6dm4zjyqznrswfbm" "https://crates.io/api/v1/crates/platform-info/2.0.5/download" ]; hash = "sha256-dTmus/3Yy09qMxMHz3GhA5zudelOinFyW5SE9KDZRRo="; name = "rust-platform-info-2.0.5.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/qm0wz8s1xr0l3vvgddbqzg586lkl59hb-rust-platform-info-2.0.5.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
