# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-iana-time-zone-0.1.63.tar.gz/sha256/1n171f5lbc7bryzmp1h30zw86zbvl5480aq02z92lcdwvvjikjdh" "https://crates.io/api/v1/crates/iana-time-zone/0.1.63/download" ]; hash = "sha256-sMkZ5d68MSrSFwArgEihe32D+AcDhlu/z+uwRYsLJ9g="; name = "rust-iana-time-zone-0.1.63.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/qwyg6d35ky29n80r8fbdp4y8szpgm7z2-rust-iana-time-zone-0.1.63.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
