# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/pytest_asyncio-1.0.0.tar.gz/sha256/0gwbqikldfy5yvyzhi71h7vicni2dchj0iarsbmf2mj47z8n6m6i" "https://files.pythonhosted.org/packages/source/p/pytest_asyncio/pytest_asyncio-1.0.0.tar.gz" ]; hash = "sha256-0VRj0T9EVuHq0llFICFrIloW94HhRPj99sW7RmfEiz8="; name = "pytest_asyncio-1.0.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/4py0wj7177n1892qmmxzlm8zk8vzsdq5-pytest_asyncio-1.0.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
