# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-rawpointer-0.2.1.tar.gz/sha256/1qy1qvj17yh957vhffnq6agq0brvylw27xgks171qrah75wmg8v0" "https://crates.io/api/v1/crates/rawpointer/0.2.1/download" ]; hash = "sha256-YKNXeTlQZRxO0PP1Izj1Oy+AnzLYOgf3KQn6E+TGweM="; name = "rust-rawpointer-0.2.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/jv4rbnknsw5h942hwz64mgl4amyx0j50-rust-rawpointer-0.2.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
