# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libassuan-3.0.1.tar.bz2/sha256/1ccly6aqyxv3hgshhls6qw177salcrawp0x4lsqs9ph3c4pg9w68" "https://gnupg.org/ftp/gcrypt/libassuan/libassuan-3.0.1.tar.bz2" ]; hash = "sha256-yPD0LmED3qSxpqSDy1VmVOlzAsdGUwj1g2N3j5XxlLE="; name = "libassuan-3.0.1.tar.bz2"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/g89dc3v334qnrj9fdfym0lfpkai8wiwf-libassuan-3.0.1.tar.bz2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
