# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/CPAN-Meta-2.150010.tar.gz/sha256/1mm3dfw3ffyzb2ikpqn9l6zyqrxijb4vyywmbx2l21ryqwp0zy74" "https://www.cpan.org/authors/id/D/DA/DAGOLDEN/CPAN-Meta-2.150010.tar.gz" ]; hash = "sha256-5PgPLsc+B0FFX5V7v8mSsWfsv6HJ4jujWN87N7hro9Y="; name = "CPAN-Meta-2.150010.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/q4hyirxy2wf5msg36gqvrailri77v41y-CPAN-Meta-2.150010.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
