# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "tmux-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''tmux-runtime-env-builder''; path = ./../sources/zj78y57ry3rnzp0fsa62a50b434skp5g-tmux-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
      (builtins.path { name = "tmux-runtime-env-builder"; path = ./../sources/zj78y57ry3rnzp0fsa62a50b434skp5g-tmux-runtime-env-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/3zb3c6jdzsw0q8apyp4i5l10fn7rcjla-libevent-2.1.12.nix).out} ${(import ../store/c2irpm67j1m0m67issl4c7gj1g4s4fym-ncurses-6.2.20210619.nix).out} ${(import ../store/aqmrkyhcdc0javqwgrl5fvas3bihh4as-tmux-3.6a.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/kgpk5aywl2c7dksm4kwjj879x7kvha2g-tmux-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
