# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-new-debug-unreachable-1.0.6.tar.gz/sha256/11phpf1mjxq6khk91yzcbd3ympm78m3ivl7xg6lg2c0lf66fy3k5" "https://crates.io/api/v1/crates/new_debug_unreachable/1.0.6/download" ]; hash = "sha256-ZQ7vjHEUMPGoef3QHUdFp97qR1vs+5AmnAZ3WYO78IY="; name = "rust-new-debug-unreachable-1.0.6.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/d3fihgc0vfdnya99rzx8d4h9wilrc45r-rust-new-debug-unreachable-1.0.6.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
