# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/clang-tools-extra-18.1.8.src.tar.xz/sha256/1wd7y1a0db4y51swlq6dmm9hrv8pvmv158yi9f10dlayv7y7g275" "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang-tools-extra-18.1.8.src.tar.xz" ]; hash = "sha256-5Yh3/Nle0QaCS9GjEnbdF+0MU63NYMp1KJ6sBlTwp/E="; name = "clang-tools-extra-18.1.8.src.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/v2i27v64jw8gw4m62326990lk5i1fxpc-clang-tools-extra-18.1.8.src.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
