# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-bytemuck-1.22.0.tar.gz/sha256/0h6m8wh7iw98cn69k53plbyqff78c2yrs32l0fy4wqdcvc8grcdn" "https://crates.io/api/v1/crates/bytemuck/1.22.0/download" ]; hash = "sha256-trH8ENusYU68A1QMnb1g6DiH/aJ3lJmMZSjxeCBH1UA="; name = "rust-bytemuck-1.22.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/sb3hk2rcwq9dag1zmlcrldsfcmh576jn-rust-bytemuck-1.22.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
