# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-gobject-sys-0.19.8.tar.gz/sha256/17lb7dfbpcg8zchwlfbc08kckwf0a7d9n5ly3pyic13f5ljpws9f" "https://crates.io/api/v1/crates/gobject-sys/0.19.8/download" ]; hash = "sha256-Lml+JS1uBBb9HZ4Wm9pRwPHJJgJsOcoh++ixu1w7i54="; name = "rust-gobject-sys-0.19.8.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/29qjmybvr7n65np1gg8c1s7dyapgil5a-rust-gobject-sys-0.19.8.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
