# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-rayon-core-1.12.1.tar.gz/sha256/1qpwim68ai5h0j7axa8ai8z0payaawv3id0lrgkqmapx7lx8fr8l" "https://crates.io/api/v1/crates/rayon-core/1.12.1/download" ]; hash = "sha256-FGWHOj39qornyxS0ODZXyqsLPooKqa6OBLBEhUyN/OI="; name = "rust-rayon-core-1.12.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/l9gn36047ihnw3c7q8a209biyz5nh51k-rust-rayon-core-1.12.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
