# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-clang-sys-1.8.1.tar.gz/sha256/1x1r9yqss76z8xwpdanw313ss6fniwc1r7dzb5ycjn0ph53kj0hb" "https://crates.io/api/v1/crates/clang-sys/1.8.1/download" ]; hash = "sha256-CwI5R4EXWMl8Wb+dHBiP1hmtRxjcqnZ5R98crbFPOfQ="; name = "rust-clang-sys-1.8.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/zvp5zjpyxfclpnfycvg5k9xr9cghryac-rust-clang-sys-1.8.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
