# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libpaper-2.0.0.tar.gz/sha256/0aipyaqp30cn919j7w5wvlgkw0v4aqsax82i2zw4wmgck8g6ax77" "https://github.com/rrthomas/libpaper/releases/download/v2.0.0/libpaper-2.0.0.tar.gz" ]; hash = "sha256-53RlHprsVU74F1GgrjRWZAM+H9288CNTSJaBcbHyNyo="; name = "libpaper-2.0.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/rbdjqan4l45xrb2yvfyvx3sxxcg00j2j-libpaper-2.0.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
