# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libgd-2.3.3.tar.xz/sha256/0qas3q9xz3wgw06dm2fj0i189rain6n60z1vyq50d5h7wbn25s1z" "https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.xz" ]; hash = "sha256-P+gi7OIHlgYK9jt8YKyxUeWEQgTSidoM4I+P3xMeWmE="; name = "libgd-2.3.3.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/rbn221sjcja49g320riz78klnmnqkglj-libgd-2.3.3.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
