# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/subversion-1.14.5.tar.bz2/sha256/18a4avism0a7b1siikkm6v2snhanlmqqzl4p8hspp2vbfvkjk2p7" "https://dlcdn.apache.org/subversion/subversion-1.14.5.tar.bz2" ]; hash = "sha256-54op53Zri3s1RJfQj3GlVkGrxTZ1zhh1WEeBquNWRKE="; name = "subversion-1.14.5.tar.bz2"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/l36rm008czw9mi359c95xqs9cbbc5vcn-subversion-1.14.5.tar.bz2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
