# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-indoc-2.0.6.tar.gz/sha256/1gbn2pkx5sgbd9lp05d2bkqpbfgazi0z3nvharh5ajah11d29izl" "https://crates.io/api/v1/crates/indoc/2.0.6/download" ]; hash = "sha256-9MckWghQSVVgVnDb8UH86rl18VyiFXBpauvp0ucVdr0="; name = "rust-indoc-2.0.6.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/m1w8bl88a8krs4lswgdfv1v7snv7mkzw-rust-indoc-2.0.6.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
