# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libotf-0.9.16.tar.gz/sha256/0sq6g3xaxw388akws6qrllp3kp2sxgk2dv4j79k6mm52rnihrnv8" "https://download.savannah.nongnu.org/releases/m17n/libotf-0.9.16.tar.gz" ]; hash = "sha256-aNsMo82i1GpmOpLsJubrWtw5LqUZG82nQmjwrvp4Bms="; name = "libotf-0.9.16.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/s6p7y2pqlrkn0izjx5b3010m07b6x2ga-libotf-0.9.16.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
