# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-indexmap-1.9.3.tar.gz/sha256/16dxmy7yvk51wvnih3a3im6fp5lmx0wx76i03n06wyak6cwhw1xx" "https://crates.io/api/v1/crates/indexmap/1.9.3/download" ]; hash = "sha256-vQcOOTNTeW6AHSCa0znolZbrTI1DDRjt5qHM7Y+vvZk="; name = "rust-indexmap-1.9.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/myln2lav9yz6wh9p3m9sn77phv85hrra-rust-indexmap-1.9.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
