# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://salsa.debian.org/iso-codes-team/iso-codes"; rev = "refs/tags/iso-codes-4.5.0"; hash = "sha256-AGnpscZPc/rMqRFZsmr48PvWq270+RgCJh100gtL3eA="; name = "iso-codes-4.5.0-checkout"; guixHash = "9lcicd7vhrcchsdsvgn3w27837z2qqb0"; fetchSubmodules = false; }
