# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-smawk-0.3.2.tar.gz/sha256/0344z1la39incggwn6nl45k8cbw2x10mr5j0qz85cdz9np0qihxp" "https://crates.io/api/v1/crates/smawk/0.3.2/download" ]; hash = "sha256-t8OIwbXpN1bQx0CWXEHogi+GZiHUGsvfYzamoWj4hAw="; name = "rust-smawk-0.3.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/h5aa5j656p77mnxsh7javianr1294678-rust-smawk-0.3.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
