# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://git.savannah.gnu.org/git/classpath.git"; rev = "e7c13ee0cf2005206fbec0eca677f8cf66d5a103"; hash = "sha256-hEdXkMAcQDGK7uylusK48xk2Z1Ai6PFuFWJwbg7nWew="; name = "classpath-0.99-1.e7c13ee0c-checkout"; guixHash = "0y51rdvvnh9w3xbczizd3brjsbfy0k04"; fetchSubmodules = false; }
