# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-crypto-common-0.1.6.tar.gz/sha256/1cvby95a6xg7kxdz5ln3rl9xh66nz66w46mm3g56ri1z5x815yqv" "https://crates.io/api/v1/crates/crypto-common/0.1.6/download" ]; hash = "sha256-G/sSUC8/xGzKG7Uawo351hjYE83D0vJbn+d1o0rya7M="; name = "rust-crypto-common-0.1.6.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/ly2w1wp0yrchn0jby16vi6nv15d9a205-rust-crypto-common-0.1.6.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
