# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/duktape-2.6.0.tar.xz/sha256/19szwxzvl2g65fw95ggvb8h0ma5bd9vvnnccn59hwnc4dida1x4n" "https://duktape.org/duktape-2.6.0.tar.xz" ]; hash = "sha256-lvSgWmyEWQ5TsYxZu3dqq6gKIFr7vZK4K+YJun/nX6c="; name = "duktape-2.6.0.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/fbnrik2lzp02p5c6qlnx781q8qf2c2b2-duktape-2.6.0.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
