# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-float-cmp-0.10.0.tar.gz/sha256/1n760i3nxd2x0zc7fkxkg3vhvdyfbvzngna006cl9s9jacaz775h" "https://crates.io/api/v1/crates/float-cmp/0.10.0/download" ]; hash = "sha256-sJzzFVMy6USZAUDZZ/9ezrcN93izT3fYB120bkcE5tg="; name = "rust-float-cmp-0.10.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/pzd4gxxv5yh2z6nzr10jz4r742avykhf-rust-float-cmp-0.10.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
