# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-num-rational-0.4.2.tar.gz/sha256/093qndy02817vpgcqjnj139im3jl7vkq4h68kykdqqh577d18ggq" "https://crates.io/api/v1/crates/num-rational/0.4.2/download" ]; hash = "sha256-+D0U2jkFYtymn8hAguc+VI4a0wjSSsze3ScgAXyzeCQ="; name = "rust-num-rational-0.4.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/zphnxpdzldccqkmnrxjcl5qxbv3h98b3-rust-num-rational-0.4.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
