# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libmnl-1.0.5.tar.bz2/sha256/09851ns07399rbz0y8slrlmnw3fn1nakr8d37pxjn5gkks8rnjr7" "mirror://netfilter.org/libmnl/libmnl-1.0.5.tar.bz2" ]; hash = "sha256-J0ubkZ7zFSv7PaOhPJUN1g1uK81UIw/+yimNA7QNBSU="; name = "libmnl-1.0.5.tar.bz2"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/m8k5sslgpchjlqxqk0vvszqqp4n8vrj6-libmnl-1.0.5.tar.bz2.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
