# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/gzip-1.2.4.tar/sha256/1rhgk2vvmdvnn6vygf0dja92ryyng00knl0kz5srb77k2kryjb2d" "https://ftp.gnu.org/gnu/gzip/gzip-1.2.4.tar" ]; hash = "sha256-TSzp8xTznJV1+RNQOwF41vsskpINuOe3sXa3ureYD+Y="; name = "gzip-1.2.4.tar"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/dzv58ywdgfkg49rrhr3c4pnvh4xgv52n-gzip-1.2.4.tar.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
