# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-fastrand-2.3.0.tar.gz/sha256/1ghiahsw1jd68df895cy5h3gzwk30hndidn3b682zmshpgmrx41p" "https://crates.io/api/v1/crates/fastrand/2.3.0/download" ]; hash = "sha256-N5Ce67tQ1y+QWcO22CwEY/L/BiyelYRcQ6bJwDVUEb4="; name = "rust-fastrand-2.3.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/k2nvar3j8xghf6pqbdca7xlyhn3yvihn-rust-fastrand-2.3.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
