# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-015/sha256/12im449abnq5gaqjmdxr5i38kmp02fa8l8wffad3jryvd58r0wzg" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-015" ]; hash = "sha256-73OQUWnbZzmaco4jipQT4NaJRiy5tyqxegXbpRIhNYo="; name = "bash52-015"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/vp9zp218za6yh8bcfyqxzxz9hlib10q2-bash52-015.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
