# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-os-pipe-1.2.1.tar.gz/sha256/10nrh0i507560rsiy4c79fajdmqgbr6dha2pbl9mncrlaq52pzaz" "https://crates.io/api/v1/crates/os_pipe/1.2.1/download" ]; hash = "sha256-X/0rClY0M1sTXVco2ExeD9cmlUuHER91BqYcUCKA2YI="; name = "rust-os-pipe-1.2.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/glm7h293fdf7drl9r5vxlrzxvj6hyksx-rust-os-pipe-1.2.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
