# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/compiler-rt-13.0.1.src.tar.xz/sha256/1z2xr9nn4mgc3hn9ark2k5y4wznpk47xppkp63bcbagr6589acvv" "https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/compiler-rt-13.0.1.src.tar.xz" ]; hash = "sha256-ezOVUDH5qcXWMHfe2w+Z135OfJliZpUsHOxVYm3KXfw="; name = "compiler-rt-13.0.1.src.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/d7pjmy9p1z8hbfmk8s6bhlp56k6qai1b-compiler-rt-13.0.1.src.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
