# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-core-foundation-0.9.4.tar.gz/sha256/13zvbbj07yk3b61b8fhwfzhy35535a583irf23vlcg59j7h9bqci" "https://crates.io/api/v1/crates/core-foundation/0.9.4/download" ]; hash = "sha256-keGV4JGpPEb3EC7HgYoqo5Th4XccOrSCWWP6A+Ra+48="; name = "rust-core-foundation-0.9.4.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/zj1swpb85lansw8y4a3dsj1nbdcyfv5j-rust-core-foundation-0.9.4.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
