# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-icu-normalizer-data-1.5.1.tar.gz/sha256/1dqcm86spcqcs4jnra81yqq3g5bpw6bvf5iz621spj5x52137s65" "https://crates.io/api/v1/crates/icu_normalizer_data/1.5.1/download" ]; hash = "sha256-xegzgii9yKuDMD8Wt5fhd5U3MPYBqWwl0Qyzqw2qDLc="; name = "rust-icu-normalizer-data-1.5.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/lsi1c2rcvdr83jdvl6h2y8lkf7ikaiyq-rust-icu-normalizer-data-1.5.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
