# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-pyo3-0.19.2.tar.gz/sha256/0f1aqx947mzsrk05zdm9w2702lj5k9s97y9w9lxwkp2avk7sd0g6" "https://crates.io/api/v1/crates/pyo3/0.19.2/download" ]; hash = "sha256-5oGmz9xK3Mk7TTz5k3SaRVIBjuCptl/AzPrXQ1LHKjg="; name = "rust-pyo3-0.19.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/47pcsymy34nqi7s6nfl08zvl5p6kj2y5-rust-pyo3-0.19.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
