# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "kbd-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''kbd-runtime-env-builder''; path = ./../sources/yg2vwldwb4jxazhg46afq46mzpw43ahz-kbd-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "kbd-runtime-env-builder"; path = ./../sources/yg2vwldwb4jxazhg46afq46mzpw43ahz-kbd-runtime-env-builder; })
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/gqs76a403zn5d0j0n280z3rzxgf1yxr0-gzip-1.14.nix).out} ${(import ../store/972qy52k93ky395q20b58z0d62whfrr4-zstd-1.5.6.nix).out} ${(import ../store/w2aaj2w4f9hdzn7aixc0lfzhqkffqjkh-bash-minimal-5.2.37.nix).out} ${(import ../store/nv4y32k2wn8jz2d1grlhky88dh9p5bg6-linux-pam-1.5.2.nix).out} ${(import ../store/lli3z9lz2m4620hplcpfrfg2ikf6ipzb-kbd-2.5.1.nix).out} ${(import ../store/009dpfa14qjk0ykg46icn9iph7qf1ny9-xz-5.4.5.nix).out} ${(import ../store/8glxd39wy20azlga2vmh5m0xg1r9galn-bzip2-1.0.8.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/qnglab9mbsi3i5zwfaahzhicdd3wxvhy-kbd-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
