# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "ld-wrapper-0";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/jsdjm29sg257a6g0mmk32s1i30r4xpi8-module-import-compiled.nix).out}"
      "${builtins.path { name = ''ld-wrapper-0-builder''; path = ./../sources/kyjsilc62yfilfww3h334bm7iqj2pdnx-ld-wrapper-0-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "ld-wrapper-0-builder"; path = ./../sources/kyjsilc62yfilfww3h334bm7iqj2pdnx-ld-wrapper-0-builder; })
      (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/b3sqqi6vn762d39w36ch8x8v29nc701q-libunistring-1.3.nix).out} ${(import ../store/sx4237qwbfhfjywmcf1m2cxnmij7vxx3-bash-minimal-5.2.37.nix).out} ${(import ../store/0mwnw93igzmjvg46sdkh81z4v5j9q4zj-binutils-2.44.nix).out} ${(import ../store/5vgf032f9dp503ri74s9vvsl6fmcgbcr-libgc-8.2.8.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/qrlyjgz0sx6c54qvhpjvn061swly3vh5-ld-wrapper-0.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
