# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/openjdk/jdk19u"; rev = "refs/tags/jdk-19.0.2-ga"; hash = "sha256-pBEHmBtIgG4Czou4C/zpBBYZEDImvXiLoA5CjOzpeyI="; name = "openjdk-19.0.2-checkout"; fetchSubmodules = false; }
