# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "guile-cv-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''guile-cv-runtime-env-builder''; path = ./../sources/a5fdy8lfccns9xlya4gb0vzzbyhlghx9-guile-cv-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
      (builtins.path { name = "guile-cv-runtime-env-builder"; path = ./../sources/a5fdy8lfccns9xlya4gb0vzzbyhlghx9-guile-cv-runtime-env-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/fiy6ja1w4db9p228fdr68s340a81wvym-libgc-8.2.8.nix).out} ${(import ../store/qmws1w2ikq4fygiaxm2vf37ck57x9ki0-guile-cv-0.4.0.nix).out} ${(import ../store/pd7y74psrbx55pj31gm6cizrjgfv770z-guile-3.0.9.nix).out} ${(import ../store/76mhhp8i3bjr2zbawqsdxnzfxd7pyz33-guile-lib-0.2.8.1.nix).out} ${(import ../store/22gmr10yi7f118509sg6p7pfcv5y76jd-vigra-c-0.0.0-2.49f5319.nix).out} ${(import ../store/h1l826sli1wp2dim9b7s6750vmi8q3wc-vigra-1.12.2.nix).out} ${(import ../store/i9gc4fc5s4khbh5pmq5zm1y7c3lspj5y-libunistring-1.3.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/rbsn41rv716pgjb50zm5lc6clgr6kf95-guile-cv-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
