# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-024/sha256/1hq23djqbr7s9y2324jq9mxr5bwdkmgizn3zgpchbsqp054k85cp" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-024" ]; hash = "sha256-lxU0SQEX6wXZfX/YH1+dja+Se01YEjGET/rkhWUbAsM="; name = "bash52-024"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/d9n1v1sd4aczw2ahnd9vglmi81f7lddi-bash52-024.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
