# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://git.elephly.net/software/guile-picture-language.git"; rev = "a1322bf11945465241ca5b742a70893f24156d12"; hash = "sha256-KdW1jwA1B/xeK9FDz0gvW8WuIHlQI1EfYzYqkT4SJQ4="; name = "guile-picture-language-0.0.1-5.a1322bf-checkout"; guixHash = "8zizcvljgf4lbc2sl1w5i9mnsa3gci4r"; fetchSubmodules = false; }
