# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-007/sha256/146lrwkn5wgxzs6vx34wl47g69zsxdy032k40qzi626b47ya6015" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-007" ]; hash = "sha256-JQCj/CHLCBM/BmSKAXzr+ifzDqGcjL6N/v3xYifP1JA="; name = "bash52-007"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/ak4c7dxsgqs391mydgv8azlh4px5hwbc-bash52-007.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
