# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-dyn-clone-1.0.19.tar.gz/sha256/01ahm5abl20480v48nxy4ffyx80cs6263q9zf0gnrxpvm6w8yyhw" "https://crates.io/api/v1/crates/dyn-clone/1.0.19/download" ]; hash = "sha256-HHqPuKn79mwfcD/hYYTRDKDunSO+W0Q2QAQIulSpUAU="; name = "rust-dyn-clone-1.0.19.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/v3kv0i9hxgrgphizqc9papvvdjk5d1lb-rust-dyn-clone-1.0.19.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
