# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-fat-macho-0.4.9.tar.gz/sha256/0idkn366wipv2l757yqfgzgibqc6jvm89gdk9kpgmvf6lv54b72c" "https://crates.io/api/v1/crates/fat-macho/0.4.9/download" ]; hash = "sha256-TJxFyqbG7fruTLO9hOqWhuEV338O+1MOFftGbsyws0U="; name = "rust-fat-macho-0.4.9.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/laqa3x1pn6r9rwp4k6gv4b7j26w55a0w-rust-fat-macho-0.4.9.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
