# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/sed-4.8.tar.gz/sha256/0alqagh0nliymz23kfjg6g9w3cr086k0sfni56gi8fhzqwa3xksk" "https://ftp.gnu.org/gnu/sed/sed-4.8.tar.gz" ]; hash = "sha256-U88+FMcfOhSfKdE6DaZBILPB0zNPujnErz5SC+BTmCo="; name = "sed-4.8.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/19skca1309cszm1habcrpnsc1rfgmww7-sed-4.8.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
