# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/trio-typing-0.10.0.tar.gz/sha256/1hvsj3w500i33ykfgh3sfkjnxhxf05incx131smshlkd562fcph6" "https://files.pythonhosted.org/packages/source/t/trio-typing/trio-typing-0.10.0.tar.gz" ]; hash = "sha256-Bl7mhCltUqirDiN0ZmMBrsNu5XR6wOemHyMCUPiQesM="; name = "trio-typing-0.10.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/42s3az3gx7vzaizc6nwnrcrcm6pq6fjg-trio-typing-0.10.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
