# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-android-tzdata-0.1.1.tar.gz/sha256/1w7ynjxrfs97xg3qlcdns4kgfpwcdv824g611fq32cag4cdr96g9" "https://crates.io/api/v1/crates/android-tzdata/0.1.1/download" ]; hash = "sha256-6ZmUGyNPMTGwC8E8ItBujF/3JtG2MYrH6ydpl7u0/vA="; name = "rust-android-tzdata-0.1.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/0iv0wdqv0mhvfiiplgxckqxakqkizhq1-rust-android-tzdata-0.1.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
