# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libunwind-1.5.0.tar.gz/sha256/05qhzcg1xag3l5m3c805np6k342gc0f3g087b7g16jidv59pccwh" "https://download.savannah.nongnu.org/releases/libunwind/libunwind-1.5.0.tar.gz" ]; hash = "sha256-kDN2U9ktShPeWQeBNxxgT5AxzbUFIDZqoeOpHh77EBc="; name = "libunwind-1.5.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/wglan9zwwda2vyzf2id5zl63ybrx38f3-libunwind-1.5.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
