# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "linux-pam-runtime-env";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
      "-C"
      "${(import ../store/lf20k6yp6882mkj8rbnmh0qgdsndhsh3-module-import-compiled.nix).out}"
      "${builtins.path { name = ''linux-pam-runtime-env-builder''; path = ./../sources/mkhadqrzsbj5n5j8l4hwsgk7l1pcx6c3-linux-pam-runtime-env-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "linux-pam-runtime-env-builder"; path = ./../sources/mkhadqrzsbj5n5j8l4hwsgk7l1pcx6c3-linux-pam-runtime-env-builder; })
      (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    allowSubstitutes = "0";
    "guix properties" = "((type . guixpkgs-runtime-env))";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/r3hlir82ik8f8cr20836356aipddp0r1-libxcrypt-4.4.38.nix).out} ${(import ../store/nv4y32k2wn8jz2d1grlhky88dh9p5bg6-linux-pam-1.5.2.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/v4p7hknq6wl66igzh2srsdv2ab2diq7i-linux-pam-runtime-env.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
