# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "openjdk-10.46-checkout";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import''; path = ./../sources/nldx2qgzrfdripdwxm3hdw9lb2y9cgyw-9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import; }}"
      "-L"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
      "-L"
      "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
      "-L"
      "${(import ../store/8499853ilh8ibcsipn20zv9n538dd51y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
      "-C"
      "${(import ../store/6s02ya5qgzp165k50snyykcgxjw0lsld-module-import-compiled.nix).out}"
      "-C"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
      "-C"
      "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
      "-C"
      "${(import ../store/8499853ilh8ibcsipn20zv9n538dd51y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
      "${builtins.path { name = ''openjdk-10.46-checkout-builder''; path = ./../sources/vc7xacs40sv0xfbjyjmb5aklx9yz6xn5-openjdk-10.46-checkout-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "openjdk-10.46-checkout-builder"; path = ./../sources/vc7xacs40sv0xfbjyjmb5aklx9yz6xn5-openjdk-10.46-checkout-builder; })
      (builtins.path { name = "9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import"; path = ./../sources/nldx2qgzrfdripdwxm3hdw9lb2y9cgyw-9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import; })
    ];
    outputHash = "sha256-fvgO2f3F74b7qFAlLAkEaYxDdHfL/8XjnFn+TlFWh0Q=";
    outputHashAlgo = "sha256";
    outputHashMode = "recursive";
    hash = "126,248,14,217,253,197,239,134,251,168,80,37,44,9,4,105,140,67,116,119,203,255,197,227,156,89,254,78,81,86,135,68";
    "hg ref changeset" = "jdk-10+46";
    "hg ref url" = "https://hg.openjdk.org/jdk/jdk";
    impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).debug} ${(import ../store/gqs76a403zn5d0j0n280z3rzxgf1yxr0-gzip-1.14.nix).out} ${(import ../store/bl5vgk4vdhsqf9wsdnvk8mhr3pcqr55j-mercurial-7.1.nix).out} ${(import ../store/h47q2hnlw8x5q16ml76kvxknsyab730j-tar-1.35.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/v7fmdr79s1995cmm50vz556s6rxndp6m-openjdk-10.46-checkout.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
