# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/open-source-parsers/jsoncpp"; rev = "refs/tags/1.9.6"; hash = "sha256-3msc3B8NyF8PUlNaAHdUDfCpcUmz8JVW2X58USJ5HRw="; name = "jsoncpp-1.9.6-checkout"; guixHash = "wg1rd1wcnwxsxbh059gxiayd3xnq6ja6"; fetchSubmodules = false; }
