# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-indoc-1.0.9.tar.gz/sha256/01l3b4ami6sck57yrn8n2z44jifph2m3jiivkws7w2njbvfrk9xz" "https://crates.io/api/v1/crates/indoc/1.0.9/download" ]; hash = "sha256-v6eZ3V7SCn40nztGOaqA10VJyBcW2exPmUybWBVZgwY="; name = "rust-indoc-1.0.9.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/dlmifr2p3n3n5gi81rlw8i76m1h292nq-rust-indoc-1.0.9.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
