# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/libxcvt-0.1.3.tar.xz/sha256/009f8kr53cv7lzsg4507cgnk9vxyrm8lgnnn6vx7vpk7hy59jad9" "https://www.x.org/releases/individual/lib/libxcvt-0.1.3.tar.xz" ]; hash = "sha256-qSmZiodn3n36NtbaR1HNvu807WMHFPL0p2ezUfJELgE="; name = "libxcvt-0.1.3.tar.xz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/n15j1r6gcaa1zv8zjc5w6v75qfj4i3dr-libxcvt-0.1.3.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
