# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-serde-1.0.219.tar.gz/sha256/1dl6nyxnsi82a197sd752128a4avm6mxnscywas1jq30srp2q3jz" "https://crates.io/api/v1/crates/serde/1.0.219/download" ]; hash = "sha256-Xw4sbtZgYBm04p5p26upWxGFRBDlNH1SUAJFbbu3hrY="; name = "rust-serde-1.0.219.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/f9cs5dqyskn37vqzkqlb3pdrb0ds443a-rust-serde-1.0.219.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
