# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "bootstrap-binaries-0";
    system = "x86_64-linux";
    builder = "${(import ../store/ahkdlnqj5180w9m1bi8wiqccmqvvy1a3-guile-bootstrap-2.0.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/6wf8wfl5w9bbzkcszys0qp8vahv6mmqm-module-import-compiled.nix).out}"
      "${builtins.path { name = ''bootstrap-binaries-0-builder''; path = ./../sources/3aw732x69lihm41dpw1zvh5ap6h8srfm-bootstrap-binaries-0-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
      (builtins.path { name = "bootstrap-binaries-0-builder"; path = ./../sources/3aw732x69lihm41dpw1zvh5ap6h8srfm-bootstrap-binaries-0-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/8k8bp20mpgp5m2gfdgzza3dafdm52pda-tar.nix).out} ${(import ../store/9yz9lnd6k7k64ld2210nlsl68wvz8d6j-static-binaries.tar.xz.nix).out} ${(import ../store/y1vqlvmrdbvmxs887fs72ilb847zmswp-xz.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/wh6zy75wlmk06f3jy4w8587fjx2cka45-bootstrap-binaries-0.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
