# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "python-ruamel.yaml.clib-0.2.12-checkout";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import''; path = ./../sources/nldx2qgzrfdripdwxm3hdw9lb2y9cgyw-9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import; }}"
      "-L"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
      "-L"
      "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
      "-L"
      "${(import ../store/8499853ilh8ibcsipn20zv9n538dd51y-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
      "-C"
      "${(import ../store/6s02ya5qgzp165k50snyykcgxjw0lsld-module-import-compiled.nix).out}"
      "-C"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
      "-C"
      "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
      "-C"
      "${(import ../store/8499853ilh8ibcsipn20zv9n538dd51y-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
      "${builtins.path { name = ''python-ruamel.yaml.clib-0.2.12-checkout-builder''; path = ./../sources/5bgviycia27rfma48bwrq1rbd0imsbqa-python-ruamel.yaml.clib-0.2.12-checkout-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import"; path = ./../sources/nldx2qgzrfdripdwxm3hdw9lb2y9cgyw-9d9kqddllvhn5mfnyif9kbsxx8q9i1bp-module-import; })
      (builtins.path { name = "python-ruamel.yaml.clib-0.2.12-checkout-builder"; path = ./../sources/5bgviycia27rfma48bwrq1rbd0imsbqa-python-ruamel.yaml.clib-0.2.12-checkout-builder; })
    ];
    outputHash = "sha256-VKiNt2WJttVjMR0z4bvdSYKOZqycRONCSPQacAy5PYo=";
    outputHashAlgo = "sha256";
    outputHashMode = "recursive";
    hash = "84,168,141,183,101,137,182,213,99,49,29,51,225,187,221,73,130,142,102,172,156,68,227,66,72,244,26,112,12,185,61,138";
    "hg ref changeset" = "0.2.12";
    "hg ref url" = "http://hg.code.sf.net/p/ruamel-yaml-clib/code";
    impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
    preferLocalBuild = "1";
    __phantom_deps = "${(import ../store/0dfgm5gypmilzv7q6vlxjw2i7c7jrgyh-guile-gnutls-5.0.1.nix).debug} ${(import ../store/gqs76a403zn5d0j0n280z3rzxgf1yxr0-gzip-1.14.nix).out} ${(import ../store/bl5vgk4vdhsqf9wsdnvk8mhr3pcqr55j-mercurial-7.1.nix).out} ${(import ../store/h47q2hnlw8x5q16ml76kvxknsyab730j-tar-1.35.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/wpz8hgaqykvsygy08vzqamavglivfr3h-python-ruamel.yaml.clib-0.2.12-checkout.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
