# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-num-integer-0.1.46.tar.gz/sha256/13w5g54a9184cqlbsq80rnxw4jj4s0d8wv75jsq5r2lms8gncsbr" "https://crates.io/api/v1/crates/num-integer/0.1.46/download" ]; hash = "sha256-eWlmH9KVilywluVsjhrQRErCu80AYb0oZgSFpEh5hY8="; name = "rust-num-integer-0.1.46.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/qa1aqihz7wxpj0m254mq67wzc706kcij-rust-num-integer-0.1.46.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
