# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-security-framework-2.11.1.tar.gz/sha256/00ldclwx78dm61v7wkach9lcx76awlrv0fdgjdwch4dmy12j4yw9" "https://crates.io/api/v1/crates/security-framework/2.11.1/download" ]; hash = "sha256-iXsiRfC1Ech4k685sDPlypzOaIJMTX52MLWh0zlljQI="; name = "rust-security-framework-2.11.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/dzl6hl08fp6swnxz3lcrnw4ys2qbf791-rust-security-framework-2.11.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
