# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/HTTP-Message-6.37.tar.gz/sha256/00nq0xnpdba4valzgvzy3fgvck1ijrksdyzb4w9q6j72hl5dln8f" "https://www.cpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6.37.tar.gz" ]; hash = "sha256-DlnaCoXiSIMTJ+v7pmeWMUy2nxv+7/ep2kStdm0H2AI="; name = "HTTP-Message-6.37.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/qg6rafn9mj0fw1l8xskjvm63ky5wwx66-HTTP-Message-6.37.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
