# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/freezegun-1.5.3.tar.gz/sha256/0pmwcjf0vxmars4kncb35pvrckp0j97lya5aqzbzy2m56d721inp" "https://files.pythonhosted.org/packages/source/f/freezegun/freezegun-1.5.3.tar.gz" ]; hash = "sha256-18YgTjOlCv/Xx6ooT0+S4E6W9y1jMTuJzqr2DZxkvF4="; name = "freezegun-1.5.3.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/94lhza127w8d3k4021kyishvs4bnily0-freezegun-1.5.3.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
