# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-linux-raw-sys-0.4.15.tar.gz/sha256/1aq7r2g7786hyxhv40spzf2nhag5xbw2axxc1k8z5k1dsgdm4v6j" "https://crates.io/api/v1/crates/linux-raw-sys/0.4.15/download" ]; hash = "sha256-0mxS29MtzPLRDKx3Jfjq5SlohftXA7Jh99Cgc57IB6s="; name = "rust-linux-raw-sys-0.4.15.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/b1pkp5rb429w18blf6nx6kv8fvsamjf6-rust-linux-raw-sys-0.4.15.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
