# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-libc-0.2.172.tar.gz/sha256/1ykz4skj7gac14znljm5clbnrhini38jkq3d60jggx3y5w2ayl6p" "https://crates.io/api/v1/crates/libc/0.2.172/download" ]; hash = "sha256-11CvBC9+9PckMG3gKdGINsJsF2WlSmo/CUy9I6cmf/o="; name = "rust-libc-0.2.172.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/7kdv0z2bvs2dlwycvraldw9bamxn58qz-rust-libc-0.2.172.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
