# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-030/sha256/13v9fqgim082dmvkslsr0hs793yzhsij2s91mjswsfhj1qip7zy3" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-030" ]; hash = "sha256-w/9zIw4SOs21rCFpIaOG3490NARZUz13bQKBGh92aY8="; name = "bash52-030"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/dk6p86z196y93mrwsjkmrmflx55ggh56-bash52-030.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
