# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "coreutils-boot0-9.1";
    system = "x86_64-linux";
    builder = "${(import ../store/ahkdlnqj5180w9m1bi8wiqccmqvvy1a3-guile-bootstrap-2.0.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
      "-C"
      "${(import ../store/0f46dz812m1jg4kg7bhsrrza3ll6m6da-module-import-compiled.nix).out}"
      "${builtins.path { name = ''coreutils-boot0-9.1-builder''; path = ./../sources/b7mllw0wifgi9zlis3s23p99qlxkrc9c-coreutils-boot0-9.1-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
      (builtins.path { name = "coreutils-boot0-9.1-builder"; path = ./../sources/b7mllw0wifgi9zlis3s23p99qlxkrc9c-coreutils-boot0-9.1-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/0lqknccaxs46psh9mnjl170i55iazx8n-gcc-mesboot-4.9.4.nix).out} ${(import ../store/j81s8mf6lw063xw26xjh6lsd5hrfn5wg-coreutils-mesboot-9.1.nix).out} ${(import ../store/8j7hrx03z771a9xicrjkvz70v23ackaq-bash-mesboot-5.2.37.nix).out} ${(import ../store/0mpc5xnckc71c6rmzj3a8lv3hjr9da7p-patch-mesboot-2.5.9.nix).out} ${(import ../store/gyby9iid49fja5zhwi7mdknwixvbclpl-glibc-mesboot-2.16.0.nix).out} ${(import ../store/f45dpx8vxhfckg2mbbns9dy1l82i74jz-coreutils-9.1.tar.xz.nix).out} ${(import ../store/4x0aqp37paxqbdf2d4drk46lllmfzds3-gawk-mesboot-3.1.8.nix).out} ${(import ../store/c77rid45sj083cd5bypixqyqvawfrf2p-grep-mesboot-3.11.nix).out} ${(import ../store/zsw49syhanpybwm0w67419mgm40jrl0w-gzip-mesboot-1.2.4.nix).out} ${(import ../store/sngwy0bcaynpm6hvl3nmszkxppyq22c1-gcc-mesboot-wrapper-4.9.4.nix).out} ${(import ../store/garxzrhvi062xdhw8575k8fzilk1gp6m-make-mesboot-3.82.nix).out} ${(import ../store/6f0h0a4v6hz95fi8nnmjbs6bqz3v0w3y-xz-mesboot-5.4.5.nix).out} ${(import ../store/9yfxwy5w493nbqifpqh9h2dgw5vi3pyb-sed-mesboot-4.8.nix).out} ${(import ../store/pw415gba6f6j52xnpd510kknm1xyjl35-tar-mesboot-1.35.nix).out} ${(import ../store/hb61lrpavpdmj93c91kk7lqdrpngswvk-make-boot0-4.4.1.nix).out} ${(import ../store/4qhpiv1bfwmj52n56zn57vamib2mvg5b-binutils-mesboot-2.20.1a.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/xnkr8lmlrxp0z61qi1p79716v46xhna6-coreutils-boot0-9.1.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
