# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-serial-test-0.5.1.tar.gz/sha256/0pchc7imdi9wv8xxnwkb9lzs6cg06ghs0gaajjb834y8837wpg70" "https://crates.io/api/v1/crates/serial_test/0.5.1/download" ]; hash = "sha256-4LzLz0DIk4GWlEo9oOEz4DGjP01rcts72jzFVuNhkF0="; name = "rust-serial-test-0.5.1.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/a6dwc9c78dck2dhx30bc9w2v1p00v7qd-rust-serial-test-0.5.1.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
