# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-self-cell-1.1.0.tar.gz/sha256/1gmxk5bvnnimcif7v1jk8ai2azfvh9djki545nd86vsnphjgrzf2" "https://crates.io/api/v1/crates/self_cell/1.1.0/download" ]; hash = "sha256-wv38JLxWb4OaLaTEKVuC230lokJThn1cZDVau1eZvb4="; name = "rust-self-cell-1.1.0.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/rpnqbfp1d23afy91rnc7clbvm7pwmwkb-rust-self-cell-1.1.0.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
