# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "linux-libre-6.12.62-guix.tar.xz";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/jsdjm29sg257a6g0mmk32s1i30r4xpi8-module-import-compiled.nix).out}"
      "${builtins.path { name = ''linux-libre-6.12.62-guix.tar.xz-builder''; path = ./../sources/m9xbgmy2hyxlrp8vv1zx70draxrk6q04-linux-libre-6.12.62-guix.tar.xz-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
      (builtins.path { name = "linux-libre-6.12.62-guix.tar.xz-builder"; path = ./../sources/m9xbgmy2hyxlrp8vv1zx70draxrk6q04-linux-libre-6.12.62-guix.tar.xz-builder; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/nrb3fvdvxkcriwqjydhgqgxqdxfh4fww-xz-5.4.5.nix).out} ${(import ../store/58080w4vcb6bwzwgjwhzxk6j6hcpslp8-linux-libre-deblob-6.12.62-gnu.nix).out} ${(import ../store/bsdvxhipmj95vi878dsvyp64flmhd206-bash-5.2.37.nix).out} ${(import ../store/f3qkpjxk9x8y4k71slhsrvac3mj91bjn-gzip-1.14.nix).out} ${(import ../store/kx6gyvq1fxmbbd0si6q1g9y3lzlqx36i-gawk-5.3.0.nix).out} ${(import ../store/xzibv9w1fxgin8lsd5p777ccvyiwv7iy-python-wrapper-3.11.14.nix).out} ${(import ../store/hyk9a17ziy3pyykysn65p220fwph4gmg-linux-6.12.62.tar.xz.nix).out} ${(import ../store/a5yvhrklbqsvr7mzpkx07ksix01y6565-tar-1.35.nix).out} ${(import ../store/cxqkzdc3w63cpgw6srijba5mwjn86dqq-patch-2.8.nix).out} ${(import ../store/jdnwi9z43hdvh8jxa6l0kqv0105p12da-coreutils-9.1.nix).out} ${(import ../store/ddzwgjs7jklv1pjsgp1m5ndm3qxm8dl0-bzip2-1.0.8.nix).out} ${(import ../store/7fpsnk1v0rwndqmkpnp06z4zrr01dq5l-diffutils-3.12.nix).out} ${(import ../store/wy1a44hmij3gs9s0jw2n1chfl2vqa5b0-grep-3.11.nix).out} ${(import ../store/pvm4xvqq7x78j6lrdsawl273hjhwmnmz-sed-4.9.nix).out} ${(import ../store/y1j97ymbfvybkfhqjhfjkbhq3069r2j7-linux-libre-deblob-check-6.12.62-gnu.nix).out} ${(import ../store/z7fj8iq3k39ap1yzxgvjg56izqi7lwma-findutils-4.10.0.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/ym74y5f32ihd440zrhsp45vvx422csh6-linux-libre-6.12.62-guix.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
