# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/tcsh-6.24.15.tar.gz/sha256/1z931m79hd7zp066s57mcifzig3byfg3ak7432jmf3rjvyjb5l6l" "https://astron.com/pub/tcsh/tcsh-6.24.15.tar.gz" "https://astron.com/pub/tcsh/old/tcsh-6.24.15.tar.gz" ]; hash = "sha256-1NCypN8yD1elGORMNZ7za7z4XWT1FG0MuP80mE4NI/0="; name = "tcsh-6.24.15.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/7b9jhwd7775wm27fbc4wxmhca3givhh3-tcsh-6.24.15.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
