# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "texinfo-6.8.tar.xz";
    system = "x86_64-linux";
    builder = "${(import ../store/ahkdlnqj5180w9m1bi8wiqccmqvvy1a3-guile-bootstrap-2.0.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
      "-C"
      "${(import ../store/6wf8wfl5w9bbzkcszys0qp8vahv6mmqm-module-import-compiled.nix).out}"
      "${builtins.path { name = ''texinfo-6.8.tar.xz-builder''; path = ./../sources/3lpkhvlc8j8d8gry9jsrlkqn4i9g0gy4-texinfo-6.8.tar.xz-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "texinfo-6.8.tar.xz-builder"; path = ./../sources/3lpkhvlc8j8d8gry9jsrlkqn4i9g0gy4-texinfo-6.8.tar.xz-builder; })
      (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
      (builtins.path { name = "texinfo-headings-single.patch"; path = ./../sources/758yzmdzmmbb8k188c65vp0drq5w1rkm-texinfo-headings-single.patch; })
    ];
    LC_CTYPE = "C.UTF-8";
    "guix properties" = "((type . origin) (patches . 1))";
    __phantom_deps = "${(import ../store/wh6zy75wlmk06f3jy4w8587fjx2cka45-bootstrap-binaries-0.nix).out} ${(import ../store/ycj1q918l6852kndr75rlwmw43k5ybys-texinfo-6.8.tar.xz.nix).out}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/z6aci9hgfrm78hfhbdrsc68x3hh5p440-texinfo-6.8.tar.xz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
