# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/bash52-005/sha256/0mykflv9qnbx3jz71l4f7isadiw9knm4qimqkwsv9cv88dafpq7c" "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-005" ]; hash = "sha256-7ODrVENos7Q1n7hGTKqdicemdDyO0HC+HH1ZnDZ101c="; name = "bash52-005"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/cqmqlql07zc3i42vkdxjcy5cnzsjq2cz-bash52-005.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
