# Generated by guix-transfer
let
  drv = builtins.derivation {
    name = "python-rfc3987-1.3.8";
    system = "x86_64-linux";
    builder = "${(import ../store/61pgsp7nm4mb175njhmwh340rd7i283k-guile-3.0.9.nix).out}/bin/guile";
    args = [
      "--no-auto-compile"
      "-L"
      "${builtins.path { name = ''qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import''; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; }}"
      "-L"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
      "-C"
      "${(import ../store/5375234zm9gqy9ama4wh0pcy6z3ryrrb-module-import-compiled.nix).out}"
      "-C"
      "${(import ../store/9fkx7053zdbzccw69ssa4ikcrhhy2rkm-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
      "${builtins.path { name = ''python-rfc3987-1.3.8-builder''; path = ./../sources/gng6615a1bgpjxm0dx3398bf2fi6wpc8-python-rfc3987-1.3.8-builder; }}"
    ];
    srcs = [
      (builtins.path { name = "sanity-check.py"; path = ./../sources/09lx08cjsa3ppv6aindzi8dh3y3nqs8r-sanity-check.py; })
      (builtins.path { name = "python-rfc3987-1.3.8-builder"; path = ./../sources/gng6615a1bgpjxm0dx3398bf2fi6wpc8-python-rfc3987-1.3.8-builder; })
      (builtins.path { name = "qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import"; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; })
    ];
    LC_CTYPE = "C.UTF-8";
    __phantom_deps = "${(import ../store/c6f0wpn95j605aaxpl344xaag78f460a-python-wrapper-3.11.14.nix).out} ${(import ../store/n7wsjwz1aaqbgx39a379z2p99zlw13rg-gcc-14.3.0.nix).out} ${(import ../store/nrb3fvdvxkcriwqjydhgqgxqdxfh4fww-xz-5.4.5.nix).out} ${(import ../store/s1pg851nljfvkdcmgsh7d5hl4ywsvaqh-glibc-2.41.nix).out} ${(import ../store/hw81y7agyvps5ljr9n197sd75j1kj05f-file-5.46.nix).out} ${(import ../store/sx4237qwbfhfjywmcf1m2cxnmij7vxx3-bash-minimal-5.2.37.nix).out} ${(import ../store/f3qkpjxk9x8y4k71slhsrvac3mj91bjn-gzip-1.14.nix).out} ${(import ../store/f884y53f29999iqn72gzs5ymdxakwla1-python-3.11.14.nix).out} ${(import ../store/kx6gyvq1fxmbbd0si6q1g9y3lzlqx36i-gawk-5.3.0.nix).out} ${(import ../store/qrlyjgz0sx6c54qvhpjvn061swly3vh5-ld-wrapper-0.nix).out} ${(import ../store/a5yvhrklbqsvr7mzpkx07ksix01y6565-tar-1.35.nix).out} ${(import ../store/qyl2nc2hjnppbsl1svr2iczbmnqb2v8r-linux-libre-headers-6.12.17.nix).out} ${(import ../store/jdnwi9z43hdvh8jxa6l0kqv0105p12da-coreutils-9.1.nix).out} ${(import ../store/0mwnw93igzmjvg46sdkh81z4v5j9q4zj-binutils-2.44.nix).out} ${(import ../store/ddzwgjs7jklv1pjsgp1m5ndm3qxm8dl0-bzip2-1.0.8.nix).out} ${(import ../store/z6gnmnr3s90dw46r8kvbyllh44znk629-make-4.4.1.nix).out} ${(import ../store/7fpsnk1v0rwndqmkpnp06z4zrr01dq5l-diffutils-3.12.nix).out} ${(import ../store/wy1a44hmij3gs9s0jw2n1chfl2vqa5b0-grep-3.11.nix).out} ${(import ../store/kjn41wniihkqg72mpk676fans5jgkrwg-python-setuptools-80.9.0.nix).out} ${(import ../store/rvmhvs0sxan4f6hwl6x6ccha3r0nqlxv-rfc3987-1.3.8.tar.gz.nix).out} ${(import ../store/s5xlhyd6fvdf1lbk92pdx54bbwz436mr-patch-2.7.6.nix).out} ${(import ../store/ymzxr25x36gi3cjp61wa7j8ic68d44vv-zstd-1.5.6.nix).out} ${(import ../store/pvm4xvqq7x78j6lrdsawl273hjhwmnmz-sed-4.9.nix).out} ${(import ../store/z7fj8iq3k39ap1yzxgvjg56izqi7lwma-findutils-4.10.0.nix).out} ${(import ../store/s1pg851nljfvkdcmgsh7d5hl4ywsvaqh-glibc-2.41.nix).static}";
  };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/zm11grhw3frdq2pv0h5a83vim24gqwzi-python-rfc3987-1.3.8.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
