# Generated by guix-transfer (download source)
let
  drv = (import ../fetch-url.nix) { urls = [ "https://bordeaux.guix.gnu.org/file/rust-getrandom-0.3.2.tar.gz/sha256/1w2mlixa1989v7czr68iji7h67yra2pbg3s480wsqjza1r2sizkk" "https://crates.io/api/v1/crates/getrandom/0.3.2/download" ]; hash = "sha256-c/6oRQ7qS6w5QESPt65Q2R8DT5QRmfzZ2QmloHqkVfA="; name = "rust-getrandom-0.3.2.tar.gz"; recursiveHash = false; executable = false; };

  # The .drv recorded when this tree was generated; consumer builder
  # scripts bake in output paths of exactly that derivation. getEnv
  # returns "" in pure evaluation — the escape hatch exists only for
  # guix-transfer's own consistency check.
  expected = "/nix/store/rphpwrvnn082jrvy91ad9hkrpj4lwlh2-rust-getrandom-0.3.2.tar.gz.drv";
in
if builtins.getEnv "GUIX_TRANSFER_SKIP_DRV_GUARD" == "1" || drv.drvPath == expected then
  drv
else
  throw "guix-transfer: ${builtins.baseNameOf expected} evaluates to ${drv.drvPath} but consumers expect ${expected}; the emitted tree is inconsistent — regenerate it with guix-transfer"
